package emoji

// MakeFaceGroup returns the FaceGroup
func MakeFaceGroup() Group {
	return Group{
		Name:       "faces",
		GroupNames: []string{"face", "head", "faces", "heads"},
		SubGroups: []subGroup{
			subGroup{
				Group:         "face",
				SubGroupNames: []string{"positive", "smile", "smiling"},
				Emojis: []emoji{
					emoji{Symbol: "😀 ", Names: []string{"grinning"}},
					emoji{Symbol: "😁 ", Names: []string{"beaming eyes"}},
					emoji{Symbol: "😂 ", Names: []string{"tears of joy"}},
					emoji{Symbol: "🤣 ", Names: []string{"rolling on the floor laughing"}},
					emoji{Symbol: "😃 ", Names: []string{"grinning big eyes"}},
					emoji{Symbol: "😄 ", Names: []string{"grinning eyes"}},
					emoji{Symbol: "😅 ", Names: []string{"grinning sweat"}},
					emoji{Symbol: "😆 ", Names: []string{"grinning squinting"}},
					emoji{Symbol: "😉 ", Names: []string{"winking"}},
					emoji{Symbol: "😊 ", Names: []string{"with eyes"}},
					emoji{Symbol: "😋 ", Names: []string{"savoring food"}},
					emoji{Symbol: "😎 ", Names: []string{"with sunglasses"}},
					emoji{Symbol: "😍 ", Names: []string{"with heart-eyes"}},
					emoji{Symbol: "😘 ", Names: []string{"blowing a kiss"}},
					emoji{Symbol: "😗 ", Names: []string{"kissing"}},
					emoji{Symbol: "😙 ", Names: []string{"kissing eyes"}},
					emoji{Symbol: "😚 ", Names: []string{"kissing closed eyes"}},
					emoji{Symbol: "☺️ ", Names: []string{"smiling"}},
					emoji{Symbol: "☺ ", Names: []string{"smiling"}},
					emoji{Symbol: "🙂 ", Names: []string{"slightly"}},
					emoji{Symbol: "🤗 ", Names: []string{"hugging"}},
					emoji{Symbol: "🤩 ", Names: []string{"star-struck"}},
				},
			},
			subGroup{
				Group:         "face",
				SubGroupNames: []string{"neutral"},
				Emojis: []emoji{
					emoji{Symbol: "🤔 ", Names: []string{"thinking"}},
					emoji{Symbol: "🤨 ", Names: []string{"raised eyebrow"}},
					emoji{Symbol: "😐 ", Names: []string{"neutral"}},
					emoji{Symbol: "😑 ", Names: []string{"expressionless"}},
					emoji{Symbol: "😶 ", Names: []string{"without mouth"}},
					emoji{Symbol: "🙄 ", Names: []string{"rolling eyes"}},
					emoji{Symbol: "😏 ", Names: []string{"smirking"}},
					emoji{Symbol: "😣 ", Names: []string{"persevering"}},
					emoji{Symbol: "😥 ", Names: []string{"sad but relieved"}},
					emoji{Symbol: "😮 ", Names: []string{"open mouth"}},
					emoji{Symbol: "🤐 ", Names: []string{"zipper-mouth"}},
					emoji{Symbol: "😯 ", Names: []string{"hushed"}},
					emoji{Symbol: "😪 ", Names: []string{"sleepy"}},
					emoji{Symbol: "😫 ", Names: []string{"tired"}},
					emoji{Symbol: "😴 ", Names: []string{"sleeping"}},
					emoji{Symbol: "😌 ", Names: []string{"relieved"}},
					emoji{Symbol: "😛 ", Names: []string{"with tongue"}},
					emoji{Symbol: "😜 ", Names: []string{"winking tongue"}},
					emoji{Symbol: "😝 ", Names: []string{"squinting tongue"}},
					emoji{Symbol: "🤤 ", Names: []string{"drooling"}},
					emoji{Symbol: "😒 ", Names: []string{"unamused"}},
					emoji{Symbol: "😓 ", Names: []string{"downcast sweat"}},
					emoji{Symbol: "😔 ", Names: []string{"pensive"}},
					emoji{Symbol: "😕 ", Names: []string{"confused"}},
					emoji{Symbol: "🙃 ", Names: []string{"upside-down"}},
					emoji{Symbol: "🤑 ", Names: []string{"money-mouth"}},
					emoji{Symbol: "😲 ", Names: []string{"astonished"}},
				},
			},
			subGroup{
				Group:         "face",
				SubGroupNames: []string{"negative"},
				Emojis: []emoji{
					emoji{Symbol: "☹️ ", Names: []string{"frowning"}},
					emoji{Symbol: "☹ ", Names: []string{"frowning"}},
					emoji{Symbol: "🙁 ", Names: []string{"slightly frowning"}},
					emoji{Symbol: "😖 ", Names: []string{"confounded"}},
					emoji{Symbol: "😞 ", Names: []string{"disappointed"}},
					emoji{Symbol: "😟 ", Names: []string{"worried"}},
					emoji{Symbol: "😤 ", Names: []string{"steam from nose"}},
					emoji{Symbol: "😢 ", Names: []string{"crying"}},
					emoji{Symbol: "😭 ", Names: []string{"loudly crying"}},
					emoji{Symbol: "😦 ", Names: []string{"frowning open mouth"}},
					emoji{Symbol: "😧 ", Names: []string{"anguished"}},
					emoji{Symbol: "😨 ", Names: []string{"fearful"}},
					emoji{Symbol: "😩 ", Names: []string{"weary"}},
					emoji{Symbol: "🤯 ", Names: []string{"exploding head"}},
					emoji{Symbol: "😬 ", Names: []string{"grimacing"}},
					emoji{Symbol: "😰 ", Names: []string{"anxious sweat"}},
					emoji{Symbol: "😱 ", Names: []string{"screaming in fear"}},
					emoji{Symbol: "😳 ", Names: []string{"flushed"}},
					emoji{Symbol: "🤪 ", Names: []string{"crazy"}},
					emoji{Symbol: "😵 ", Names: []string{"dizzy"}},
					emoji{Symbol: "😡 ", Names: []string{"pouting"}},
					emoji{Symbol: "😠 ", Names: []string{"angry"}},
					emoji{Symbol: "🤬 ", Names: []string{"symbols on mouth"}},
				},
			},
			subGroup{
				SubGroupNames: []string{"sick"},
				Group:         "face",
				Emojis: []emoji{
					emoji{Symbol: "😷 ", Names: []string{"medical mask"}},
					emoji{Symbol: "🤒 ", Names: []string{"thermometer"}},
					emoji{Symbol: "🤕 ", Names: []string{"head-bandage"}},
					emoji{Symbol: "🤢 ", Names: []string{"nauseated"}},
					emoji{Symbol: "🤮 ", Names: []string{"vomiting"}},
					emoji{Symbol: "🤧 ", Names: []string{"sneezing"}},
				},
			},
			subGroup{
				Group:         "face",
				SubGroupNames: []string{"role"},
				Emojis: []emoji{
					emoji{Symbol: "😇 ", Names: []string{"smiling halo"}},
					emoji{Symbol: "🤠 ", Names: []string{"cowboy hat"}},
					emoji{Symbol: "🤡 ", Names: []string{"clown"}},
					emoji{Symbol: "🤥 ", Names: []string{"lying"}},
					emoji{Symbol: "🤫 ", Names: []string{"shushing"}},
					emoji{Symbol: "🤭 ", Names: []string{"hand over mouth"}},
					emoji{Symbol: "🧐 ", Names: []string{"monocle"}},
					emoji{Symbol: "🤓 ", Names: []string{"nerd"}},
				},
			},
			subGroup{
				Group:         "face",
				SubGroupNames: []string{"fantasy"},
				Emojis: []emoji{
					emoji{Symbol: "😈 ", Names: []string{"smiling horns"}},
					emoji{Symbol: "👿 ", Names: []string{"angry horns"}},
					emoji{Symbol: "👹 ", Names: []string{"ogre"}},
					emoji{Symbol: "👺 ", Names: []string{"goblin"}},
					emoji{Symbol: "💀 ", Names: []string{"skull"}},
					emoji{Symbol: "☠️ ", Names: []string{"skull and crossbones"}},
					emoji{Symbol: "☠ ", Names: []string{"skull and crossbones"}},
					emoji{Symbol: "👻 ", Names: []string{"ghost"}},
					emoji{Symbol: "👽 ", Names: []string{"alien"}},
					emoji{Symbol: "👾 ", Names: []string{"alien monster"}},
					emoji{Symbol: "🤖 ", Names: []string{"robot"}},
					emoji{Symbol: "💩 ", Names: []string{"pile of poo", "crap", "shit"}},
				},
			},
			subGroup{
				SubGroupNames: []string{"cat"},
				Group:         "face",
				Emojis: []emoji{
					emoji{Symbol: "😺 ", Names: []string{"grinning"}},
					emoji{Symbol: "😸 ", Names: []string{"grinning smiling eyes"}},
					emoji{Symbol: "😹 ", Names: []string{"tears of joy"}},
					emoji{Symbol: "😻 ", Names: []string{"smiling heart-eyes"}},
					emoji{Symbol: "😼 ", Names: []string{"wry smile"}},
					emoji{Symbol: "😽 ", Names: []string{"kissing"}},
					emoji{Symbol: "🙀 ", Names: []string{"weary"}},
					emoji{Symbol: "😿 ", Names: []string{"crying"}},
					emoji{Symbol: "😾 ", Names: []string{"pouting"}},
				},
			},
			subGroup{
				Group:         "face",
				SubGroupNames: []string{"monkey"},
				Emojis: []emoji{
					emoji{Symbol: "🙈 ", Names: []string{"see-no-evil", "see"}},
					emoji{Symbol: "🙉 ", Names: []string{"hear-no-evil", "hear"}},
					emoji{Symbol: "🙊 ", Names: []string{"speak-no-evil", "speak"}},
				},
			},
		},
	}
}
