package emoji

func MakePeopleGroup() Group {
	return Group{
		Name:       "people",
		GroupNames: []string{"people", "child", "boy", "girl"},
		SubGroups: []subGroup{
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"baby"},
				Emojis: []emoji{
					emoji{"👶", []string{"baby"}},
					emoji{"👶🏻", []string{"baby: light skin tone"}},
					emoji{"👶🏼", []string{"baby: medium-light skin tone"}},
					emoji{"👶🏽", []string{"baby: medium skin tone"}},
					emoji{"👶🏾", []string{"baby: medium-dark skin tone"}},
					emoji{"👶🏿", []string{"baby: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"child"},
				Emojis: []emoji{
					emoji{"🧒", []string{"child"}},
					emoji{"🧒🏻", []string{"child: light skin tone"}},
					emoji{"🧒🏼", []string{"child: medium-light skin tone"}},
					emoji{"🧒🏽", []string{"child: medium skin tone"}},
					emoji{"🧒🏾", []string{"child: medium-dark skin tone"}},
					emoji{"🧒🏿", []string{"child: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"boy"},
				Emojis: []emoji{
					emoji{"👦", []string{"boy"}},
					emoji{"👦🏻", []string{"boy: light skin tone"}},
					emoji{"👦🏼", []string{"boy: medium-light skin tone"}},
					emoji{"👦🏽", []string{"boy: medium skin tone"}},
					emoji{"👦🏾", []string{"boy: medium-dark skin tone"}},
					emoji{"👦🏿", []string{"boy: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"girl"},
				Emojis: []emoji{
					emoji{"👧", []string{"girl"}},
					emoji{"👧🏻", []string{"girl: light skin tone"}},
					emoji{"👧🏼", []string{"girl: medium-light skin tone"}},
					emoji{"👧🏽", []string{"girl: medium skin tone"}},
					emoji{"👧🏾", []string{"girl: medium-dark skin tone"}},
					emoji{"👧🏿", []string{"girl: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"adult"},
				Emojis: []emoji{
					emoji{"🧑", []string{"adult"}},
					emoji{"🧑🏻", []string{"adult: light skin tone"}},
					emoji{"🧑🏼", []string{"adult: medium-light skin tone"}},
					emoji{"🧑🏽", []string{"adult: medium skin tone"}},
					emoji{"🧑🏾", []string{"adult: medium-dark skin tone"}},
					emoji{"🧑🏿", []string{"adult: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"man"},
				Emojis: []emoji{
					emoji{"👨", []string{"man"}},
					emoji{"👨🏻", []string{"man: light skin tone"}},
					emoji{"👨🏼", []string{"man: medium-light skin tone"}},
					emoji{"👨🏽", []string{"man: medium skin tone"}},
					emoji{"👨🏾", []string{"man: medium-dark skin tone"}},
					emoji{"👨🏿", []string{"man: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"woman"},
				Emojis: []emoji{
					emoji{"👩", []string{"woman"}},
					emoji{"👩🏻", []string{"woman: light skin tone"}},
					emoji{"👩🏼", []string{"woman: medium-light skin tone"}},
					emoji{"👩🏽", []string{"woman: medium skin tone"}},
					emoji{"👩🏾", []string{"woman: medium-dark skin tone"}},
					emoji{"👩🏿", []string{"woman: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"older adult"},
				Emojis: []emoji{
					emoji{"🧓", []string{"older adult"}},
					emoji{"🧓🏻", []string{"older adult: light skin tone"}},
					emoji{"🧓🏼", []string{"older adult: medium-light skin tone"}},
					emoji{"🧓🏽", []string{"older adult: medium skin tone"}},
					emoji{"🧓🏾", []string{"older adult: medium-dark skin tone"}},
					emoji{"🧓🏿", []string{"older adult: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"old man"},
				Emojis: []emoji{
					emoji{"👴", []string{"old man"}},
					emoji{"👴🏻", []string{"old man: light skin tone"}},
					emoji{"👴🏼", []string{"old man: medium-light skin tone"}},
					emoji{"👴🏽", []string{"old man: medium skin tone"}},
					emoji{"👴🏾", []string{"old man: medium-dark skin tone"}},
					emoji{"👴🏿", []string{"old man: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"old woman"},
				Emojis: []emoji{
					emoji{"👵", []string{"old woman"}},
					emoji{"👵🏻", []string{"old woman: light skin tone"}},
					emoji{"👵🏼", []string{"old woman: medium-light skin tone"}},
					emoji{"👵🏽", []string{"old woman: medium skin tone"}},
					emoji{"👵🏾", []string{"old woman: medium-dark skin tone"}},
					emoji{"👵🏿", []string{"old woman: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"health-worker"},
				Emojis: []emoji{
					emoji{"👨‍⚕️", []string{"man health worker"}},
					emoji{"👨‍⚕", []string{"man health worker"}},
					emoji{"👨🏻‍⚕️", []string{"man health worker: light skin tone"}},
					emoji{"👨🏻‍⚕", []string{"man health worker: light skin tone"}},
					emoji{"👨🏼‍⚕️", []string{"man health worker: medium-light skin tone"}},
					emoji{"👨🏼‍⚕", []string{"man health worker: medium-light skin tone"}},
					emoji{"👨🏽‍⚕️", []string{"man health worker: medium skin tone"}},
					emoji{"👨🏽‍⚕", []string{"man health worker: medium skin tone"}},
					emoji{"👨🏾‍⚕️", []string{"man health worker: medium-dark skin tone"}},
					emoji{"👨🏾‍⚕", []string{"man health worker: medium-dark skin tone"}},
					emoji{"👨🏿‍⚕️", []string{"man health worker: dark skin tone"}},
					emoji{"👨🏿‍⚕", []string{"man health worker: dark skin tone"}},
					emoji{"👩‍⚕️", []string{"woman health worker"}},
					emoji{"👩‍⚕", []string{"woman health worker"}},
					emoji{"👩🏻‍⚕️", []string{"woman health worker: light skin tone"}},
					emoji{"👩🏻‍⚕", []string{"woman health worker: light skin tone"}},
					emoji{"👩🏼‍⚕️", []string{"woman health worker: medium-light skin tone"}},
					emoji{"👩🏼‍⚕", []string{"woman health worker: medium-light skin tone"}},
					emoji{"👩🏽‍⚕️", []string{"woman health worker: medium skin tone"}},
					emoji{"👩🏽‍⚕", []string{"woman health worker: medium skin tone"}},
					emoji{"👩🏾‍⚕️", []string{"woman health worker: medium-dark skin tone"}},
					emoji{"👩🏾‍⚕", []string{"woman health worker: medium-dark skin tone"}},
					emoji{"👩🏿‍⚕️", []string{"woman health worker: dark skin tone"}},
					emoji{"👩🏿‍⚕", []string{"woman health worker: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"student"},
				Emojis: []emoji{
					emoji{"👨‍🎓", []string{"man student"}},
					emoji{"👨🏻‍🎓", []string{"man student: light skin tone"}},
					emoji{"👨🏼‍🎓", []string{"man student: medium-light skin tone"}},
					emoji{"👨🏽‍🎓", []string{"man student: medium skin tone"}},
					emoji{"👨🏾‍🎓", []string{"man student: medium-dark skin tone"}},
					emoji{"👨🏿‍🎓", []string{"man student: dark skin tone"}},
					emoji{"👩‍🎓", []string{"woman student"}},
					emoji{"👩🏻‍🎓", []string{"woman student: light skin tone"}},
					emoji{"👩🏼‍🎓", []string{"woman student: medium-light skin tone"}},
					emoji{"👩🏽‍🎓", []string{"woman student: medium skin tone"}},
					emoji{"👩🏾‍🎓", []string{"woman student: medium-dark skin tone"}},
					emoji{"👩🏿‍🎓", []string{"woman student: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"teacher"},
				Emojis: []emoji{
					emoji{"👨‍🏫", []string{"man teacher"}},
					emoji{"👨🏻‍🏫", []string{"man teacher: light skin tone"}},
					emoji{"👨🏼‍🏫", []string{"man teacher: medium-light skin tone"}},
					emoji{"👨🏽‍🏫", []string{"man teacher: medium skin tone"}},
					emoji{"👨🏾‍🏫", []string{"man teacher: medium-dark skin tone"}},
					emoji{"👨🏿‍🏫", []string{"man teacher: dark skin tone"}},
					emoji{"👩‍🏫", []string{"woman teacher"}},
					emoji{"👩🏻‍🏫", []string{"woman teacher: light skin tone"}},
					emoji{"👩🏼‍🏫", []string{"woman teacher: medium-light skin tone"}},
					emoji{"👩🏽‍🏫", []string{"woman teacher: medium skin tone"}},
					emoji{"👩🏾‍🏫", []string{"woman teacher: medium-dark skin tone"}},
					emoji{"👩🏿‍🏫", []string{"woman teacher: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"judge"},
				Emojis: []emoji{
					emoji{"👨‍⚖️", []string{"man judge"}},
					emoji{"👨‍⚖", []string{"man judge"}},
					emoji{"👨🏻‍⚖️", []string{"man judge: light skin tone"}},
					emoji{"👨🏻‍⚖", []string{"man judge: light skin tone"}},
					emoji{"👨🏼‍⚖️", []string{"man judge: medium-light skin tone"}},
					emoji{"👨🏼‍⚖", []string{"man judge: medium-light skin tone"}},
					emoji{"👨🏽‍⚖️", []string{"man judge: medium skin tone"}},
					emoji{"👨🏽‍⚖", []string{"man judge: medium skin tone"}},
					emoji{"👨🏾‍⚖️", []string{"man judge: medium-dark skin tone"}},
					emoji{"👨🏾‍⚖", []string{"man judge: medium-dark skin tone"}},
					emoji{"👨🏿‍⚖️", []string{"man judge: dark skin tone"}},
					emoji{"👨🏿‍⚖", []string{"man judge: dark skin tone"}},
					emoji{"👩‍⚖️", []string{"woman judge"}},
					emoji{"👩‍⚖", []string{"woman judge"}},
					emoji{"👩🏻‍⚖️", []string{"woman judge: light skin tone"}},
					emoji{"👩🏻‍⚖", []string{"woman judge: light skin tone"}},
					emoji{"👩🏼‍⚖️", []string{"woman judge: medium-light skin tone"}},
					emoji{"👩🏼‍⚖", []string{"woman judge: medium-light skin tone"}},
					emoji{"👩🏽‍⚖️", []string{"woman judge: medium skin tone"}},
					emoji{"👩🏽‍⚖", []string{"woman judge: medium skin tone"}},
					emoji{"👩🏾‍⚖️", []string{"woman judge: medium-dark skin tone"}},
					emoji{"👩🏾‍⚖", []string{"woman judge: medium-dark skin tone"}},
					emoji{"👩🏿‍⚖️", []string{"woman judge: dark skin tone"}},
					emoji{"👩🏿‍⚖", []string{"woman judge: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"farmer"},
				Emojis: []emoji{
					emoji{"👨‍🌾", []string{"man farmer"}},
					emoji{"👨🏻‍🌾", []string{"man farmer: light skin tone"}},
					emoji{"👨🏼‍🌾", []string{"man farmer: medium-light skin tone"}},
					emoji{"👨🏽‍🌾", []string{"man farmer: medium skin tone"}},
					emoji{"👨🏾‍🌾", []string{"man farmer: medium-dark skin tone"}},
					emoji{"👨🏿‍🌾", []string{"man farmer: dark skin tone"}},
					emoji{"👩‍🌾", []string{"woman farmer"}},
					emoji{"👩🏻‍🌾", []string{"woman farmer: light skin tone"}},
					emoji{"👩🏼‍🌾", []string{"woman farmer: medium-light skin tone"}},
					emoji{"👩🏽‍🌾", []string{"woman farmer: medium skin tone"}},
					emoji{"👩🏾‍🌾", []string{"woman farmer: medium-dark skin tone"}},
					emoji{"👩🏿‍🌾", []string{"woman farmer: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"cook"},
				Emojis: []emoji{
					emoji{"👨‍🍳", []string{"man cook"}},
					emoji{"👨🏻‍🍳", []string{"man cook: light skin tone"}},
					emoji{"👨🏼‍🍳", []string{"man cook: medium-light skin tone"}},
					emoji{"👨🏽‍🍳", []string{"man cook: medium skin tone"}},
					emoji{"👨🏾‍🍳", []string{"man cook: medium-dark skin tone"}},
					emoji{"👨🏿‍🍳", []string{"man cook: dark skin tone"}},
					emoji{"👩‍🍳", []string{"woman cook"}},
					emoji{"👩🏻‍🍳", []string{"woman cook: light skin tone"}},
					emoji{"👩🏼‍🍳", []string{"woman cook: medium-light skin tone"}},
					emoji{"👩🏽‍🍳", []string{"woman cook: medium skin tone"}},
					emoji{"👩🏾‍🍳", []string{"woman cook: medium-dark skin tone"}},
					emoji{"👩🏿‍🍳", []string{"woman cook: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"mechanic"},
				Emojis: []emoji{
					emoji{"👨‍🔧", []string{"man mechanic"}},
					emoji{"👨🏻‍🔧", []string{"man mechanic: light skin tone"}},
					emoji{"👨🏼‍🔧", []string{"man mechanic: medium-light skin tone"}},
					emoji{"👨🏽‍🔧", []string{"man mechanic: medium skin tone"}},
					emoji{"👨🏾‍🔧", []string{"man mechanic: medium-dark skin tone"}},
					emoji{"👨🏿‍🔧", []string{"man mechanic: dark skin tone"}},
					emoji{"👩‍🔧", []string{"woman mechanic"}},
					emoji{"👩🏻‍🔧", []string{"woman mechanic: light skin tone"}},
					emoji{"👩🏼‍🔧", []string{"woman mechanic: medium-light skin tone"}},
					emoji{"👩🏽‍🔧", []string{"woman mechanic: medium skin tone"}},
					emoji{"👩🏾‍🔧", []string{"woman mechanic: medium-dark skin tone"}},
					emoji{"👩🏿‍🔧", []string{"woman mechanic: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"factory-worker"},
				Emojis: []emoji{
					emoji{"👨‍🏭", []string{"man factory worker"}},
					emoji{"👨🏻‍🏭", []string{"man factory worker: light skin tone"}},
					emoji{"👨🏼‍🏭", []string{"man factory worker: medium-light skin tone"}},
					emoji{"👨🏽‍🏭", []string{"man factory worker: medium skin tone"}},
					emoji{"👨🏾‍🏭", []string{"man factory worker: medium-dark skin tone"}},
					emoji{"👨🏿‍🏭", []string{"man factory worker: dark skin tone"}},
					emoji{"👩‍🏭", []string{"woman factory worker"}},
					emoji{"👩🏻‍🏭", []string{"woman factory worker: light skin tone"}},
					emoji{"👩🏼‍🏭", []string{"woman factory worker: medium-light skin tone"}},
					emoji{"👩🏽‍🏭", []string{"woman factory worker: medium skin tone"}},
					emoji{"👩🏾‍🏭", []string{"woman factory worker: medium-dark skin tone"}},
					emoji{"👩🏿‍🏭", []string{"woman factory worker: dark skin tone"}},
					emoji{"👨‍💼", []string{"man office worker"}},
					emoji{"👨🏻‍💼", []string{"man office worker: light skin tone"}},
					emoji{"👨🏼‍💼", []string{"man office worker: medium-light skin tone"}},
					emoji{"👨🏽‍💼", []string{"man office worker: medium skin tone"}},
					emoji{"👨🏾‍💼", []string{"man office worker: medium-dark skin tone"}},
					emoji{"👨🏿‍💼", []string{"man office worker: dark skin tone"}},
					emoji{"👩‍💼", []string{"woman office worker"}},
					emoji{"👩🏻‍💼", []string{"woman office worker: light skin tone"}},
					emoji{"👩🏼‍💼", []string{"woman office worker: medium-light skin tone"}},
					emoji{"👩🏽‍💼", []string{"woman office worker: medium skin tone"}},
					emoji{"👩🏾‍💼", []string{"woman office worker: medium-dark skin tone"}},
					emoji{"👩🏿‍💼", []string{"woman office worker: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"scientist"},
				Emojis: []emoji{
					emoji{"👨‍🔬", []string{"man scientist"}},
					emoji{"👨🏻‍🔬", []string{"man scientist: light skin tone"}},
					emoji{"👨🏼‍🔬", []string{"man scientist: medium-light skin tone"}},
					emoji{"👨🏽‍🔬", []string{"man scientist: medium skin tone"}},
					emoji{"👨🏾‍🔬", []string{"man scientist: medium-dark skin tone"}},
					emoji{"👨🏿‍🔬", []string{"man scientist: dark skin tone"}},
					emoji{"👩‍🔬", []string{"woman scientist"}},
					emoji{"👩🏻‍🔬", []string{"woman scientist: light skin tone"}},
					emoji{"👩🏼‍🔬", []string{"woman scientist: medium-light skin tone"}},
					emoji{"👩🏽‍🔬", []string{"woman scientist: medium skin tone"}},
					emoji{"👩🏾‍🔬", []string{"woman scientist: medium-dark skin tone"}},
					emoji{"👩🏿‍🔬", []string{"woman scientist: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"technologist"},
				Emojis: []emoji{
					emoji{"👨‍💻", []string{"man technologist"}},
					emoji{"👨🏻‍💻", []string{"man technologist: light skin tone"}},
					emoji{"👨🏼‍💻", []string{"man technologist: medium-light skin tone"}},
					emoji{"👨🏽‍💻", []string{"man technologist: medium skin tone"}},
					emoji{"👨🏾‍💻", []string{"man technologist: medium-dark skin tone"}},
					emoji{"👨🏿‍💻", []string{"man technologist: dark skin tone"}},
					emoji{"👩‍💻", []string{"woman technologist"}},
					emoji{"👩🏻‍💻", []string{"woman technologist: light skin tone"}},
					emoji{"👩🏼‍💻", []string{"woman technologist: medium-light skin tone"}},
					emoji{"👩🏽‍💻", []string{"woman technologist: medium skin tone"}},
					emoji{"👩🏾‍💻", []string{"woman technologist: medium-dark skin tone"}},
					emoji{"👩🏿‍💻", []string{"woman technologist: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"singer"},
				Emojis: []emoji{
					emoji{"👨‍🎤", []string{"man singer"}},
					emoji{"👨🏻‍🎤", []string{"man singer: light skin tone"}},
					emoji{"👨🏼‍🎤", []string{"man singer: medium-light skin tone"}},
					emoji{"👨🏽‍🎤", []string{"man singer: medium skin tone"}},
					emoji{"👨🏾‍🎤", []string{"man singer: medium-dark skin tone"}},
					emoji{"👨🏿‍🎤", []string{"man singer: dark skin tone"}},
					emoji{"👩‍🎤", []string{"woman singer"}},
					emoji{"👩🏻‍🎤", []string{"woman singer: light skin tone"}},
					emoji{"👩🏼‍🎤", []string{"woman singer: medium-light skin tone"}},
					emoji{"👩🏽‍🎤", []string{"woman singer: medium skin tone"}},
					emoji{"👩🏾‍🎤", []string{"woman singer: medium-dark skin tone"}},
					emoji{"👩🏿‍🎤", []string{"woman singer: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"artist"},
				Emojis: []emoji{
					emoji{"👨‍🎨", []string{"man artist"}},
					emoji{"👨🏻‍🎨", []string{"man artist: light skin tone"}},
					emoji{"👨🏼‍🎨", []string{"man artist: medium-light skin tone"}},
					emoji{"👨🏽‍🎨", []string{"man artist: medium skin tone"}},
					emoji{"👨🏾‍🎨", []string{"man artist: medium-dark skin tone"}},
					emoji{"👨🏿‍🎨", []string{"man artist: dark skin tone"}},
					emoji{"👩‍🎨", []string{"woman artist"}},
					emoji{"👩🏻‍🎨", []string{"woman artist: light skin tone"}},
					emoji{"👩🏼‍🎨", []string{"woman artist: medium-light skin tone"}},
					emoji{"👩🏽‍🎨", []string{"woman artist: medium skin tone"}},
					emoji{"👩🏾‍🎨", []string{"woman artist: medium-dark skin tone"}},
					emoji{"👩🏿‍🎨", []string{"woman artist: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"pilot"},
				Emojis: []emoji{
					emoji{"👨‍✈️", []string{"man pilot"}},
					emoji{"👨‍✈", []string{"man pilot"}},
					emoji{"👨🏻‍✈️", []string{"man pilot: light skin tone"}},
					emoji{"👨🏻‍✈", []string{"man pilot: light skin tone"}},
					emoji{"👨🏼‍✈️", []string{"man pilot: medium-light skin tone"}},
					emoji{"👨🏼‍✈", []string{"man pilot: medium-light skin tone"}},
					emoji{"👨🏽‍✈️", []string{"man pilot: medium skin tone"}},
					emoji{"👨🏽‍✈", []string{"man pilot: medium skin tone"}},
					emoji{"👨🏾‍✈️", []string{"man pilot: medium-dark skin tone"}},
					emoji{"👨🏾‍✈", []string{"man pilot: medium-dark skin tone"}},
					emoji{"👨🏿‍✈️", []string{"man pilot: dark skin tone"}},
					emoji{"👨🏿‍✈", []string{"man pilot: dark skin tone"}},
					emoji{"👩‍✈️", []string{"woman pilot"}},
					emoji{"👩‍✈", []string{"woman pilot"}},
					emoji{"👩🏻‍✈️", []string{"woman pilot: light skin tone"}},
					emoji{"👩🏻‍✈", []string{"woman pilot: light skin tone"}},
					emoji{"👩🏼‍✈️", []string{"woman pilot: medium-light skin tone"}},
					emoji{"👩🏼‍✈", []string{"woman pilot: medium-light skin tone"}},
					emoji{"👩🏽‍✈️", []string{"woman pilot: medium skin tone"}},
					emoji{"👩🏽‍✈", []string{"woman pilot: medium skin tone"}},
					emoji{"👩🏾‍✈️", []string{"woman pilot: medium-dark skin tone"}},
					emoji{"👩🏾‍✈", []string{"woman pilot: medium-dark skin tone"}},
					emoji{"👩🏿‍✈️", []string{"woman pilot: dark skin tone"}},
					emoji{"👩🏿‍✈", []string{"woman pilot: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"astronaut"},
				Emojis: []emoji{
					emoji{"👨‍🚀", []string{"man astronaut"}},
					emoji{"👨🏻‍🚀", []string{"man astronaut: light skin tone"}},
					emoji{"👨🏼‍🚀", []string{"man astronaut: medium-light skin tone"}},
					emoji{"👨🏽‍🚀", []string{"man astronaut: medium skin tone"}},
					emoji{"👨🏾‍🚀", []string{"man astronaut: medium-dark skin tone"}},
					emoji{"👨🏿‍🚀", []string{"man astronaut: dark skin tone"}},
					emoji{"👩‍🚀", []string{"woman astronaut"}},
					emoji{"👩🏻‍🚀", []string{"woman astronaut: light skin tone"}},
					emoji{"👩🏼‍🚀", []string{"woman astronaut: medium-light skin tone"}},
					emoji{"👩🏽‍🚀", []string{"woman astronaut: medium skin tone"}},
					emoji{"👩🏾‍🚀", []string{"woman astronaut: medium-dark skin tone"}},
					emoji{"👩🏿‍🚀", []string{"woman astronaut: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"firefighter"},
				Emojis: []emoji{
					emoji{"👨‍🚒", []string{"man firefighter"}},
					emoji{"👨🏻‍🚒", []string{"man firefighter: light skin tone"}},
					emoji{"👨🏼‍🚒", []string{"man firefighter: medium-light skin tone"}},
					emoji{"👨🏽‍🚒", []string{"man firefighter: medium skin tone"}},
					emoji{"👨🏾‍🚒", []string{"man firefighter: medium-dark skin tone"}},
					emoji{"👨🏿‍🚒", []string{"man firefighter: dark skin tone"}},
					emoji{"👩‍🚒", []string{"woman firefighter"}},
					emoji{"👩🏻‍🚒", []string{"woman firefighter: light skin tone"}},
					emoji{"👩🏼‍🚒", []string{"woman firefighter: medium-light skin tone"}},
					emoji{"👩🏽‍🚒", []string{"woman firefighter: medium skin tone"}},
					emoji{"👩🏾‍🚒", []string{"woman firefighter: medium-dark skin tone"}},
					emoji{"👩🏿‍🚒", []string{"woman firefighter: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"police-officer"},
				Emojis: []emoji{
					emoji{"👮", []string{"police officer"}},
					emoji{"👮🏻", []string{"police officer: light skin tone"}},
					emoji{"👮🏼", []string{"police officer: medium-light skin tone"}},
					emoji{"👮🏽", []string{"police officer: medium skin tone"}},
					emoji{"👮🏾", []string{"police officer: medium-dark skin tone"}},
					emoji{"👮🏿", []string{"police officer: dark skin tone"}},
					emoji{"👮‍♂️", []string{"man police officer"}},
					emoji{"👮‍♂", []string{"man police officer"}},
					emoji{"👮🏻‍♂️", []string{"man police officer: light skin tone"}},
					emoji{"👮🏻‍♂", []string{"man police officer: light skin tone"}},
					emoji{"👮🏼‍♂️", []string{"man police officer: medium-light skin tone"}},
					emoji{"👮🏼‍♂", []string{"man police officer: medium-light skin tone"}},
					emoji{"👮🏽‍♂️", []string{"man police officer: medium skin tone"}},
					emoji{"👮🏽‍♂", []string{"man police officer: medium skin tone"}},
					emoji{"👮🏾‍♂️", []string{"man police officer: medium-dark skin tone"}},
					emoji{"👮🏾‍♂", []string{"man police officer: medium-dark skin tone"}},
					emoji{"👮🏿‍♂️", []string{"man police officer: dark skin tone"}},
					emoji{"👮🏿‍♂", []string{"man police officer: dark skin tone"}},
					emoji{"👮‍♀️", []string{"woman police officer"}},
					emoji{"👮‍♀", []string{"woman police officer"}},
					emoji{"👮🏻‍♀️", []string{"woman police officer: light skin tone"}},
					emoji{"👮🏻‍♀", []string{"woman police officer: light skin tone"}},
					emoji{"👮🏼‍♀️", []string{"woman police officer: medium-light skin tone"}},
					emoji{"👮🏼‍♀", []string{"woman police officer: medium-light skin tone"}},
					emoji{"👮🏽‍♀️", []string{"woman police officer: medium skin tone"}},
					emoji{"👮🏽‍♀", []string{"woman police officer: medium skin tone"}},
					emoji{"👮🏾‍♀️", []string{"woman police officer: medium-dark skin tone"}},
					emoji{"👮🏾‍♀", []string{"woman police officer: medium-dark skin tone"}},
					emoji{"👮🏿‍♀️", []string{"woman police officer: dark skin tone"}},
					emoji{"👮🏿‍♀", []string{"woman police officer: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"detective"},
				Emojis: []emoji{
					emoji{"🕵️", []string{"detective"}},
					emoji{"🕵", []string{"detective"}},
					emoji{"🕵🏻", []string{"detective: light skin tone"}},
					emoji{"🕵🏼", []string{"detective: medium-light skin tone"}},
					emoji{"🕵🏽", []string{"detective: medium skin tone"}},
					emoji{"🕵🏾", []string{"detective: medium-dark skin tone"}},
					emoji{"🕵🏿", []string{"detective: dark skin tone"}},
					emoji{"🕵️‍♂️", []string{"man detective"}},
					emoji{"🕵‍♂️", []string{"man detective"}},
					emoji{"🕵️‍♂", []string{"man detective"}},
					emoji{"🕵‍♂", []string{"man detective"}},
					emoji{"🕵🏻‍♂️", []string{"man detective: light skin tone"}},
					emoji{"🕵🏻‍♂", []string{"man detective: light skin tone"}},
					emoji{"🕵🏼‍♂️", []string{"man detective: medium-light skin tone"}},
					emoji{"🕵🏼‍♂", []string{"man detective: medium-light skin tone"}},
					emoji{"🕵🏽‍♂️", []string{"man detective: medium skin tone"}},
					emoji{"🕵🏽‍♂", []string{"man detective: medium skin tone"}},
					emoji{"🕵🏾‍♂️", []string{"man detective: medium-dark skin tone"}},
					emoji{"🕵🏾‍♂", []string{"man detective: medium-dark skin tone"}},
					emoji{"🕵🏿‍♂️", []string{"man detective: dark skin tone"}},
					emoji{"🕵🏿‍♂", []string{"man detective: dark skin tone"}},
					emoji{"🕵️‍♀️", []string{"woman detective"}},
					emoji{"🕵‍♀️", []string{"woman detective"}},
					emoji{"🕵️‍♀", []string{"woman detective"}},
					emoji{"🕵‍♀", []string{"woman detective"}},
					emoji{"🕵🏻‍♀️", []string{"woman detective: light skin tone"}},
					emoji{"🕵🏻‍♀", []string{"woman detective: light skin tone"}},
					emoji{"🕵🏼‍♀️", []string{"woman detective: medium-light skin tone"}},
					emoji{"🕵🏼‍♀", []string{"woman detective: medium-light skin tone"}},
					emoji{"🕵🏽‍♀️", []string{"woman detective: medium skin tone"}},
					emoji{"🕵🏽‍♀", []string{"woman detective: medium skin tone"}},
					emoji{"🕵🏾‍♀️", []string{"woman detective: medium-dark skin tone"}},
					emoji{"🕵🏾‍♀", []string{"woman detective: medium-dark skin tone"}},
					emoji{"🕵🏿‍♀️", []string{"woman detective: dark skin tone"}},
					emoji{"🕵🏿‍♀", []string{"woman detective: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"guard"},
				Emojis: []emoji{
					emoji{"💂", []string{"guard"}},
					emoji{"💂🏻", []string{"guard: light skin tone"}},
					emoji{"💂🏼", []string{"guard: medium-light skin tone"}},
					emoji{"💂🏽", []string{"guard: medium skin tone"}},
					emoji{"💂🏾", []string{"guard: medium-dark skin tone"}},
					emoji{"💂🏿", []string{"guard: dark skin tone"}},
					emoji{"💂‍♂️", []string{"man guard"}},
					emoji{"💂‍♂", []string{"man guard"}},
					emoji{"💂🏻‍♂️", []string{"man guard: light skin tone"}},
					emoji{"💂🏻‍♂", []string{"man guard: light skin tone"}},
					emoji{"💂🏼‍♂️", []string{"man guard: medium-light skin tone"}},
					emoji{"💂🏼‍♂", []string{"man guard: medium-light skin tone"}},
					emoji{"💂🏽‍♂️", []string{"man guard: medium skin tone"}},
					emoji{"💂🏽‍♂", []string{"man guard: medium skin tone"}},
					emoji{"💂🏾‍♂️", []string{"man guard: medium-dark skin tone"}},
					emoji{"💂🏾‍♂", []string{"man guard: medium-dark skin tone"}},
					emoji{"💂🏿‍♂️", []string{"man guard: dark skin tone"}},
					emoji{"💂🏿‍♂", []string{"man guard: dark skin tone"}},
					emoji{"💂‍♀️", []string{"woman guard"}},
					emoji{"💂‍♀", []string{"woman guard"}},
					emoji{"💂🏻‍♀️", []string{"woman guard: light skin tone"}},
					emoji{"💂🏻‍♀", []string{"woman guard: light skin tone"}},
					emoji{"💂🏼‍♀️", []string{"woman guard: medium-light skin tone"}},
					emoji{"💂🏼‍♀", []string{"woman guard: medium-light skin tone"}},
					emoji{"💂🏽‍♀️", []string{"woman guard: medium skin tone"}},
					emoji{"💂🏽‍♀", []string{"woman guard: medium skin tone"}},
					emoji{"💂🏾‍♀️", []string{"woman guard: medium-dark skin tone"}},
					emoji{"💂🏾‍♀", []string{"woman guard: medium-dark skin tone"}},
					emoji{"💂🏿‍♀️", []string{"woman guard: dark skin tone"}},
					emoji{"💂🏿‍♀", []string{"woman guard: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"construction-worker"},
				Emojis: []emoji{
					emoji{"👷", []string{"construction worker"}},
					emoji{"👷🏻", []string{"construction worker: light skin tone"}},
					emoji{"👷🏼", []string{"construction worker: medium-light skin tone"}},
					emoji{"👷🏽", []string{"construction worker: medium skin tone"}},
					emoji{"👷🏾", []string{"construction worker: medium-dark skin tone"}},
					emoji{"👷🏿", []string{"construction worker: dark skin tone"}},
					emoji{"👷‍♂️", []string{"man construction worker"}},
					emoji{"👷‍♂", []string{"man construction worker"}},
					emoji{"👷🏻‍♂️", []string{"man construction worker: light skin tone"}},
					emoji{"👷🏻‍♂", []string{"man construction worker: light skin tone"}},
					emoji{"👷🏼‍♂️", []string{"man construction worker: medium-light skin tone"}},
					emoji{"👷🏼‍♂", []string{"man construction worker: medium-light skin tone"}},
					emoji{"👷🏽‍♂️", []string{"man construction worker: medium skin tone"}},
					emoji{"👷🏽‍♂", []string{"man construction worker: medium skin tone"}},
					emoji{"👷🏾‍♂️", []string{"man construction worker: medium-dark skin tone"}},
					emoji{"👷🏾‍♂", []string{"man construction worker: medium-dark skin tone"}},
					emoji{"👷🏿‍♂️", []string{"man construction worker: dark skin tone"}},
					emoji{"👷🏿‍♂", []string{"man construction worker: dark skin tone"}},
					emoji{"👷‍♀️", []string{"woman construction worker"}},
					emoji{"👷‍♀", []string{"woman construction worker"}},
					emoji{"👷🏻‍♀️", []string{"woman construction worker: light skin tone"}},
					emoji{"👷🏻‍♀", []string{"woman construction worker: light skin tone"}},
					emoji{"👷🏼‍♀️", []string{"woman construction worker: medium-light skin tone"}},
					emoji{"👷🏼‍♀", []string{"woman construction worker: medium-light skin tone"}},
					emoji{"👷🏽‍♀️", []string{"woman construction worker: medium skin tone"}},
					emoji{"👷🏽‍♀", []string{"woman construction worker: medium skin tone"}},
					emoji{"👷🏾‍♀️", []string{"woman construction worker: medium-dark skin tone"}},
					emoji{"👷🏾‍♀", []string{"woman construction worker: medium-dark skin tone"}},
					emoji{"👷🏿‍♀️", []string{"woman construction worker: dark skin tone"}},
					emoji{"👷🏿‍♀", []string{"woman construction worker: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"prince"},
				Emojis: []emoji{
					emoji{"🤴", []string{"prince"}},
					emoji{"🤴🏻", []string{"prince: light skin tone"}},
					emoji{"🤴🏼", []string{"prince: medium-light skin tone"}},
					emoji{"🤴🏽", []string{"prince: medium skin tone"}},
					emoji{"🤴🏾", []string{"prince: medium-dark skin tone"}},
					emoji{"🤴🏿", []string{"prince: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"princess"},
				Emojis: []emoji{
					emoji{"👸", []string{"princess"}},
					emoji{"👸🏻", []string{"princess: light skin tone"}},
					emoji{"👸🏼", []string{"princess: medium-light skin tone"}},
					emoji{"👸🏽", []string{"princess: medium skin tone"}},
					emoji{"👸🏾", []string{"princess: medium-dark skin tone"}},
					emoji{"👸🏿", []string{"princess: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"turban"},
				Emojis: []emoji{
					emoji{"👳", []string{"person wearing turban"}},
					emoji{"👳🏻", []string{"person wearing turban: light skin tone"}},
					emoji{"👳🏼", []string{"person wearing turban: medium-light skin tone"}},
					emoji{"👳🏽", []string{"person wearing turban: medium skin tone"}},
					emoji{"👳🏾", []string{"person wearing turban: medium-dark skin tone"}},
					emoji{"👳🏿", []string{"person wearing turban: dark skin tone"}},
					emoji{"👳‍♂️", []string{"man wearing turban"}},
					emoji{"👳‍♂", []string{"man wearing turban"}},
					emoji{"👳🏻‍♂️", []string{"man wearing turban: light skin tone"}},
					emoji{"👳🏻‍♂", []string{"man wearing turban: light skin tone"}},
					emoji{"👳🏼‍♂️", []string{"man wearing turban: medium-light skin tone"}},
					emoji{"👳🏼‍♂", []string{"man wearing turban: medium-light skin tone"}},
					emoji{"👳🏽‍♂️", []string{"man wearing turban: medium skin tone"}},
					emoji{"👳🏽‍♂", []string{"man wearing turban: medium skin tone"}},
					emoji{"👳🏾‍♂️", []string{"man wearing turban: medium-dark skin tone"}},
					emoji{"👳🏾‍♂", []string{"man wearing turban: medium-dark skin tone"}},
					emoji{"👳🏿‍♂️", []string{"man wearing turban: dark skin tone"}},
					emoji{"👳🏿‍♂", []string{"man wearing turban: dark skin tone"}},
					emoji{"👳‍♀️", []string{"woman wearing turban"}},
					emoji{"👳‍♀", []string{"woman wearing turban"}},
					emoji{"👳🏻‍♀️", []string{"woman wearing turban: light skin tone"}},
					emoji{"👳🏻‍♀", []string{"woman wearing turban: light skin tone"}},
					emoji{"👳🏼‍♀️", []string{"woman wearing turban: medium-light skin tone"}},
					emoji{"👳🏼‍♀", []string{"woman wearing turban: medium-light skin tone"}},
					emoji{"👳🏽‍♀️", []string{"woman wearing turban: medium skin tone"}},
					emoji{"👳🏽‍♀", []string{"woman wearing turban: medium skin tone"}},
					emoji{"👳🏾‍♀️", []string{"woman wearing turban: medium-dark skin tone"}},
					emoji{"👳🏾‍♀", []string{"woman wearing turban: medium-dark skin tone"}},
					emoji{"👳🏿‍♀️", []string{"woman wearing turban: dark skin tone"}},
					emoji{"👳🏿‍♀", []string{"woman wearing turban: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"chinese-cap"},
				Emojis: []emoji{
					emoji{"👲", []string{"man with Chinese cap"}},
					emoji{"👲🏻", []string{"man with Chinese cap: light skin tone"}},
					emoji{"👲🏼", []string{"man with Chinese cap: medium-light skin tone"}},
					emoji{"👲🏽", []string{"man with Chinese cap: medium skin tone"}},
					emoji{"👲🏾", []string{"man with Chinese cap: medium-dark skin tone"}},
					emoji{"👲🏿", []string{"man with Chinese cap: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"headscarf"},
				Emojis: []emoji{
					emoji{"🧕", []string{"woman with headscarf"}},
					emoji{"🧕🏻", []string{"woman with headscarf: light skin tone"}},
					emoji{"🧕🏼", []string{"woman with headscarf: medium-light skin tone"}},
					emoji{"🧕🏽", []string{"woman with headscarf: medium skin tone"}},
					emoji{"🧕🏾", []string{"woman with headscarf: medium-dark skin tone"}},
					emoji{"🧕🏿", []string{"woman with headscarf: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"bearded"},
				Emojis: []emoji{
					emoji{"🧔", []string{"bearded person"}},
					emoji{"🧔🏻", []string{"bearded person: light skin tone"}},
					emoji{"🧔🏼", []string{"bearded person: medium-light skin tone"}},
					emoji{"🧔🏽", []string{"bearded person: medium skin tone"}},
					emoji{"🧔🏾", []string{"bearded person: medium-dark skin tone"}},
					emoji{"🧔🏿", []string{"bearded person: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"blonde"},
				Emojis: []emoji{
					emoji{"👱", []string{"blond-haired person"}},
					emoji{"👱🏻", []string{"blond-haired person: light skin tone"}},
					emoji{"👱🏼", []string{"blond-haired person: medium-light skin tone"}},
					emoji{"👱🏽", []string{"blond-haired person: medium skin tone"}},
					emoji{"👱🏾", []string{"blond-haired person: medium-dark skin tone"}},
					emoji{"👱🏿", []string{"blond-haired person: dark skin tone"}},
					emoji{"👱‍♂️", []string{"blond-haired man"}},
					emoji{"👱‍♂", []string{"blond-haired man"}},
					emoji{"👱🏻‍♂️", []string{"blond-haired man: light skin tone"}},
					emoji{"👱🏻‍♂", []string{"blond-haired man: light skin tone"}},
					emoji{"👱🏼‍♂️", []string{"blond-haired man: medium-light skin tone"}},
					emoji{"👱🏼‍♂", []string{"blond-haired man: medium-light skin tone"}},
					emoji{"👱🏽‍♂️", []string{"blond-haired man: medium skin tone"}},
					emoji{"👱🏽‍♂", []string{"blond-haired man: medium skin tone"}},
					emoji{"👱🏾‍♂️", []string{"blond-haired man: medium-dark skin tone"}},
					emoji{"👱🏾‍♂", []string{"blond-haired man: medium-dark skin tone"}},
					emoji{"👱🏿‍♂️", []string{"blond-haired man: dark skin tone"}},
					emoji{"👱🏿‍♂", []string{"blond-haired man: dark skin tone"}},
					emoji{"👱‍♀️", []string{"blond-haired woman"}},
					emoji{"👱‍♀", []string{"blond-haired woman"}},
					emoji{"👱🏻‍♀️", []string{"blond-haired woman: light skin tone"}},
					emoji{"👱🏻‍♀", []string{"blond-haired woman: light skin tone"}},
					emoji{"👱🏼‍♀️", []string{"blond-haired woman: medium-light skin tone"}},
					emoji{"👱🏼‍♀", []string{"blond-haired woman: medium-light skin tone"}},
					emoji{"👱🏽‍♀️", []string{"blond-haired woman: medium skin tone"}},
					emoji{"👱🏽‍♀", []string{"blond-haired woman: medium skin tone"}},
					emoji{"👱🏾‍♀️", []string{"blond-haired woman: medium-dark skin tone"}},
					emoji{"👱🏾‍♀", []string{"blond-haired woman: medium-dark skin tone"}},
					emoji{"👱🏿‍♀️", []string{"blond-haired woman: dark skin tone"}},
					emoji{"👱🏿‍♀", []string{"blond-haired woman: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"health-worker"},
				Emojis: []emoji{
					emoji{"🤵", []string{"man in tuxedo"}},
					emoji{"🤵🏻", []string{"man in tuxedo: light skin tone"}},
					emoji{"🤵🏼", []string{"man in tuxedo: medium-light skin tone"}},
					emoji{"🤵🏽", []string{"man in tuxedo: medium skin tone"}},
					emoji{"🤵🏾", []string{"man in tuxedo: medium-dark skin tone"}},
					emoji{"🤵🏿", []string{"man in tuxedo: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"health-worker"},
				Emojis: []emoji{
					emoji{"👰", []string{"bride with veil"}},
					emoji{"👰🏻", []string{"bride with veil: light skin tone"}},
					emoji{"👰🏼", []string{"bride with veil: medium-light skin tone"}},
					emoji{"👰🏽", []string{"bride with veil: medium skin tone"}},
					emoji{"👰🏾", []string{"bride with veil: medium-dark skin tone"}},
					emoji{"👰🏿", []string{"bride with veil: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"health-worker"},
				Emojis: []emoji{
					emoji{"🤰", []string{"pregnant woman"}},
					emoji{"🤰🏻", []string{"pregnant woman: light skin tone"}},
					emoji{"🤰🏼", []string{"pregnant woman: medium-light skin tone"}},
					emoji{"🤰🏽", []string{"pregnant woman: medium skin tone"}},
					emoji{"🤰🏾", []string{"pregnant woman: medium-dark skin tone"}},
					emoji{"🤰🏿", []string{"pregnant woman: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"health-worker"},
				Emojis: []emoji{
					emoji{"🤱", []string{"breast-feeding"}},
					emoji{"🤱🏻", []string{"breast-feeding: light skin tone"}},
					emoji{"🤱🏼", []string{"breast-feeding: medium-light skin tone"}},
					emoji{"🤱🏽", []string{"breast-feeding: medium skin tone"}},
					emoji{"🤱🏾", []string{"breast-feeding: medium-dark skin tone"}},
					emoji{"🤱🏿", []string{"breast-feeding: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"baby-angel"},
				Emojis: []emoji{
					emoji{"👼", []string{"baby-angel"}},
					emoji{"👼🏻", []string{"baby angel: light skin tone"}},
					emoji{"👼🏼", []string{"baby angel: medium-light skin tone"}},
					emoji{"👼🏽", []string{"baby angel: medium skin tone"}},
					emoji{"👼🏾", []string{"baby angel: medium-dark skin tone"}},
					emoji{"👼🏿", []string{"baby angel: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"Santa-Claus"},
				Emojis: []emoji{
					emoji{"🎅", []string{"Santa Claus"}},
					emoji{"🎅🏻", []string{"Santa Claus: light skin tone"}},
					emoji{"🎅🏼", []string{"Santa Claus: medium-light skin tone"}},
					emoji{"🎅🏽", []string{"Santa Claus: medium skin tone"}},
					emoji{"🎅🏾", []string{"Santa Claus: medium-dark skin tone"}},
					emoji{"🎅🏿", []string{"Santa Claus: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"Santa-Claus"},
				Emojis: []emoji{
					emoji{"🤶", []string{"Mrs. Claus"}},
					emoji{"🤶🏻", []string{"Mrs. Claus: light skin tone"}},
					emoji{"🤶🏼", []string{"Mrs. Claus: medium-light skin tone"}},
					emoji{"🤶🏽", []string{"Mrs. Claus: medium skin tone"}},
					emoji{"🤶🏾", []string{"Mrs. Claus: medium-dark skin tone"}},
					emoji{"🤶🏿", []string{"Mrs. Claus: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"mage"},
				Emojis: []emoji{
					emoji{"🧙", []string{"mage"}},
					emoji{"🧙🏻", []string{"mage: light skin tone"}},
					emoji{"🧙🏼", []string{"mage: medium-light skin tone"}},
					emoji{"🧙🏽", []string{"mage: medium skin tone"}},
					emoji{"🧙🏾", []string{"mage: medium-dark skin tone"}},
					emoji{"🧙🏿", []string{"mage: dark skin tone"}},
					emoji{"🧙‍♀️", []string{"woman mage"}},
					emoji{"🧙‍♀", []string{"woman mage"}},
					emoji{"🧙🏻‍♀️", []string{"woman mage: light skin tone"}},
					emoji{"🧙🏻‍♀", []string{"woman mage: light skin tone"}},
					emoji{"🧙🏼‍♀️", []string{"woman mage: medium-light skin tone"}},
					emoji{"🧙🏼‍♀", []string{"woman mage: medium-light skin tone"}},
					emoji{"🧙🏽‍♀️", []string{"woman mage: medium skin tone"}},
					emoji{"🧙🏽‍♀", []string{"woman mage: medium skin tone"}},
					emoji{"🧙🏾‍♀️", []string{"woman mage: medium-dark skin tone"}},
					emoji{"🧙🏾‍♀", []string{"woman mage: medium-dark skin tone"}},
					emoji{"🧙🏿‍♀️", []string{"woman mage: dark skin tone"}},
					emoji{"🧙🏿‍♀", []string{"woman mage: dark skin tone"}},
					emoji{"🧙‍♂️", []string{"man mage"}},
					emoji{"🧙‍♂", []string{"man mage"}},
					emoji{"🧙🏻‍♂️", []string{"man mage: light skin tone"}},
					emoji{"🧙🏻‍♂", []string{"man mage: light skin tone"}},
					emoji{"🧙🏼‍♂️", []string{"man mage: medium-light skin tone"}},
					emoji{"🧙🏼‍♂", []string{"man mage: medium-light skin tone"}},
					emoji{"🧙🏽‍♂️", []string{"man mage: medium skin tone"}},
					emoji{"🧙🏽‍♂", []string{"man mage: medium skin tone"}},
					emoji{"🧙🏾‍♂️", []string{"man mage: medium-dark skin tone"}},
					emoji{"🧙🏾‍♂", []string{"man mage: medium-dark skin tone"}},
					emoji{"🧙🏿‍♂️", []string{"man mage: dark skin tone"}},
					emoji{"🧙🏿‍♂", []string{"man mage: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"fairy"},
				Emojis: []emoji{
					emoji{"🧚🏻", []string{"fairy: light skin tone"}},
					emoji{"🧚🏼", []string{"fairy: medium-light skin tone"}},
					emoji{"🧚🏽", []string{"fairy: medium skin tone"}},
					emoji{"🧚🏾", []string{"fairy: medium-dark skin tone"}},
					emoji{"🧚🏿", []string{"fairy: dark skin tone"}},
					emoji{"🧚‍♀️", []string{"woman fairy"}},
					emoji{"🧚‍♀", []string{"woman fairy"}},
					emoji{"🧚🏻‍♀️", []string{"woman fairy: light skin tone"}},
					emoji{"🧚🏻‍♀", []string{"woman fairy: light skin tone"}},
					emoji{"🧚🏼‍♀️", []string{"woman fairy: medium-light skin tone"}},
					emoji{"🧚🏼‍♀", []string{"woman fairy: medium-light skin tone"}},
					emoji{"🧚🏽‍♀️", []string{"woman fairy: medium skin tone"}},
					emoji{"🧚🏽‍♀", []string{"woman fairy: medium skin tone"}},
					emoji{"🧚🏾‍♀️", []string{"woman fairy: medium-dark skin tone"}},
					emoji{"🧚🏾‍♀", []string{"woman fairy: medium-dark skin tone"}},
					emoji{"🧚🏿‍♀️", []string{"woman fairy: dark skin tone"}},
					emoji{"🧚🏿‍♀", []string{"woman fairy: dark skin tone"}},
					emoji{"🧚‍♂️", []string{"man fairy"}},
					emoji{"🧚‍♂", []string{"man fairy"}},
					emoji{"🧚🏻‍♂️", []string{"man fairy: light skin tone"}},
					emoji{"🧚🏻‍♂", []string{"man fairy: light skin tone"}},
					emoji{"🧚🏼‍♂️", []string{"man fairy: medium-light skin tone"}},
					emoji{"🧚🏼‍♂", []string{"man fairy: medium-light skin tone"}},
					emoji{"🧚🏽‍♂️", []string{"man fairy: medium skin tone"}},
					emoji{"🧚🏽‍♂", []string{"man fairy: medium skin tone"}},
					emoji{"🧚🏾‍♂️", []string{"man fairy: medium-dark skin tone"}},
					emoji{"🧚🏾‍♂", []string{"man fairy: medium-dark skin tone"}},
					emoji{"🧚🏿‍♂️", []string{"man fairy: dark skin tone"}},
					emoji{"🧚🏿‍♂", []string{"man fairy: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"vampire"},
				Emojis: []emoji{
					emoji{"🧛🏻", []string{"vampire: light skin tone"}},
					emoji{"🧛🏼", []string{"vampire: medium-light skin tone"}},
					emoji{"🧛🏽", []string{"vampire: medium skin tone"}},
					emoji{"🧛🏾", []string{"vampire: medium-dark skin tone"}},
					emoji{"🧛🏿", []string{"vampire: dark skin tone"}},
					emoji{"🧛‍♀️", []string{"woman vampire"}},
					emoji{"🧛‍♀", []string{"woman vampire"}},
					emoji{"🧛🏻‍♀️", []string{"woman vampire: light skin tone"}},
					emoji{"🧛🏻‍♀", []string{"woman vampire: light skin tone"}},
					emoji{"🧛🏼‍♀️", []string{"woman vampire: medium-light skin tone"}},
					emoji{"🧛🏼‍♀", []string{"woman vampire: medium-light skin tone"}},
					emoji{"🧛🏽‍♀️", []string{"woman vampire: medium skin tone"}},
					emoji{"🧛🏽‍♀", []string{"woman vampire: medium skin tone"}},
					emoji{"🧛🏾‍♀️", []string{"woman vampire: medium-dark skin tone"}},
					emoji{"🧛🏾‍♀", []string{"woman vampire: medium-dark skin tone"}},
					emoji{"🧛🏿‍♀️", []string{"woman vampire: dark skin tone"}},
					emoji{"🧛🏿‍♀", []string{"woman vampire: dark skin tone"}},
					emoji{"🧛‍♂️", []string{"man vampire"}},
					emoji{"🧛‍♂", []string{"man vampire"}},
					emoji{"🧛🏻‍♂️", []string{"man vampire: light skin tone"}},
					emoji{"🧛🏻‍♂", []string{"man vampire: light skin tone"}},
					emoji{"🧛🏼‍♂️", []string{"man vampire: medium-light skin tone"}},
					emoji{"🧛🏼‍♂", []string{"man vampire: medium-light skin tone"}},
					emoji{"🧛🏽‍♂️", []string{"man vampire: medium skin tone"}},
					emoji{"🧛🏽‍♂", []string{"man vampire: medium skin tone"}},
					emoji{"🧛🏾‍♂️", []string{"man vampire: medium-dark skin tone"}},
					emoji{"🧛🏾‍♂", []string{"man vampire: medium-dark skin tone"}},
					emoji{"🧛🏿‍♂️", []string{"man vampire: dark skin tone"}},
					emoji{"🧛🏿‍♂", []string{"man vampire: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"merperson"},
				Emojis: []emoji{
					emoji{"🧜🏻", []string{"merperson: light skin tone"}},
					emoji{"🧜🏼", []string{"merperson: medium-light skin tone"}},
					emoji{"🧜🏽", []string{"merperson: medium skin tone"}},
					emoji{"🧜🏾", []string{"merperson: medium-dark skin tone"}},
					emoji{"🧜🏿", []string{"merperson: dark skin tone"}},
					emoji{"🧜‍♀️", []string{"mermaid"}},
					emoji{"🧜‍♀", []string{"mermaid"}},
					emoji{"🧜🏻‍♀️", []string{"mermaid: light skin tone"}},
					emoji{"🧜🏻‍♀", []string{"mermaid: light skin tone"}},
					emoji{"🧜🏼‍♀️", []string{"mermaid: medium-light skin tone"}},
					emoji{"🧜🏼‍♀", []string{"mermaid: medium-light skin tone"}},
					emoji{"🧜🏽‍♀️", []string{"mermaid: medium skin tone"}},
					emoji{"🧜🏽‍♀", []string{"mermaid: medium skin tone"}},
					emoji{"🧜🏾‍♀️", []string{"mermaid: medium-dark skin tone"}},
					emoji{"🧜🏾‍♀", []string{"mermaid: medium-dark skin tone"}},
					emoji{"🧜🏿‍♀️", []string{"mermaid: dark skin tone"}},
					emoji{"🧜🏿‍♀", []string{"mermaid: dark skin tone"}},
					emoji{"🧜‍♂️", []string{"merman"}},
					emoji{"🧜‍♂", []string{"merman"}},
					emoji{"🧜🏻‍♂️", []string{"merman: light skin tone"}},
					emoji{"🧜🏻‍♂", []string{"merman: light skin tone"}},
					emoji{"🧜🏼‍♂️", []string{"merman: medium-light skin tone"}},
					emoji{"🧜🏼‍♂", []string{"merman: medium-light skin tone"}},
					emoji{"🧜🏽‍♂️", []string{"merman: medium skin tone"}},
					emoji{"🧜🏽‍♂", []string{"merman: medium skin tone"}},
					emoji{"🧜🏾‍♂️", []string{"merman: medium-dark skin tone"}},
					emoji{"🧜🏾‍♂", []string{"merman: medium-dark skin tone"}},
					emoji{"🧜🏿‍♂️", []string{"merman: dark skin tone"}},
					emoji{"🧜🏿‍♂", []string{"merman: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"elf"},
				Emojis: []emoji{
					emoji{"🧝🏻", []string{"elf: light skin tone"}},
					emoji{"🧝🏼", []string{"elf: medium-light skin tone"}},
					emoji{"🧝🏽", []string{"elf: medium skin tone"}},
					emoji{"🧝🏾", []string{"elf: medium-dark skin tone"}},
					emoji{"🧝🏿", []string{"elf: dark skin tone"}},
					emoji{"🧝‍♀️", []string{"woman elf"}},
					emoji{"🧝‍♀", []string{"woman elf"}},
					emoji{"🧝🏻‍♀️", []string{"woman elf: light skin tone"}},
					emoji{"🧝🏻‍♀", []string{"woman elf: light skin tone"}},
					emoji{"🧝🏼‍♀️", []string{"woman elf: medium-light skin tone"}},
					emoji{"🧝🏼‍♀", []string{"woman elf: medium-light skin tone"}},
					emoji{"🧝🏽‍♀️", []string{"woman elf: medium skin tone"}},
					emoji{"🧝🏽‍♀", []string{"woman elf: medium skin tone"}},
					emoji{"🧝🏾‍♀️", []string{"woman elf: medium-dark skin tone"}},
					emoji{"🧝🏾‍♀", []string{"woman elf: medium-dark skin tone"}},
					emoji{"🧝🏿‍♀️", []string{"woman elf: dark skin tone"}},
					emoji{"🧝🏿‍♀", []string{"woman elf: dark skin tone"}},
					emoji{"🧝‍♂️", []string{"man elf"}},
					emoji{"🧝‍♂", []string{"man elf"}},
					emoji{"🧝🏻‍♂️", []string{"man elf: light skin tone"}},
					emoji{"🧝🏻‍♂", []string{"man elf: light skin tone"}},
					emoji{"🧝🏼‍♂️", []string{"man elf: medium-light skin tone"}},
					emoji{"🧝🏼‍♂", []string{"man elf: medium-light skin tone"}},
					emoji{"🧝🏽‍♂️", []string{"man elf: medium skin tone"}},
					emoji{"🧝🏽‍♂", []string{"man elf: medium skin tone"}},
					emoji{"🧝🏾‍♂️", []string{"man elf: medium-dark skin tone"}},
					emoji{"🧝🏾‍♂", []string{"man elf: medium-dark skin tone"}},
					emoji{"🧝🏿‍♂️", []string{"man elf: dark skin tone"}},
					emoji{"🧝🏿‍♂", []string{"man elf: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"genie"},
				Emojis: []emoji{
					emoji{"🧞‍♀️", []string{"woman genie"}},
					emoji{"🧞‍♀", []string{"woman genie"}},
					emoji{"🧞‍♂️", []string{"man genie"}},
					emoji{"🧞‍♂", []string{"man genie"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"zombie"},
				Emojis: []emoji{
					emoji{"🧟‍♀️", []string{"woman zombie"}},
					emoji{"🧟‍♀", []string{"woman zombie"}},
					emoji{"🧟‍♂️", []string{"man zombie"}},
					emoji{"🧟‍♂", []string{"man zombie"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"frowning"},
				Emojis: []emoji{
					emoji{"🙍", []string{"person frowning"}},
					emoji{"🙍🏻", []string{"person frowning: light skin tone"}},
					emoji{"🙍🏼", []string{"person frowning: medium-light skin tone"}},
					emoji{"🙍🏽", []string{"person frowning: medium skin tone"}},
					emoji{"🙍🏾", []string{"person frowning: medium-dark skin tone"}},
					emoji{"🙍🏿", []string{"person frowning: dark skin tone"}},
					emoji{"🙍‍♂️", []string{"man frowning"}},
					emoji{"🙍‍♂", []string{"man frowning"}},
					emoji{"🙍🏻‍♂️", []string{"man frowning: light skin tone"}},
					emoji{"🙍🏻‍♂", []string{"man frowning: light skin tone"}},
					emoji{"🙍🏼‍♂️", []string{"man frowning: medium-light skin tone"}},
					emoji{"🙍🏼‍♂", []string{"man frowning: medium-light skin tone"}},
					emoji{"🙍🏽‍♂️", []string{"man frowning: medium skin tone"}},
					emoji{"🙍🏽‍♂", []string{"man frowning: medium skin tone"}},
					emoji{"🙍🏾‍♂️", []string{"man frowning: medium-dark skin tone"}},
					emoji{"🙍🏾‍♂", []string{"man frowning: medium-dark skin tone"}},
					emoji{"🙍🏿‍♂️", []string{"man frowning: dark skin tone"}},
					emoji{"🙍🏿‍♂", []string{"man frowning: dark skin tone"}},
					emoji{"🙍‍♀️", []string{"woman frowning"}},
					emoji{"🙍‍♀", []string{"woman frowning"}},
					emoji{"🙍🏻‍♀️", []string{"woman frowning: light skin tone"}},
					emoji{"🙍🏻‍♀", []string{"woman frowning: light skin tone"}},
					emoji{"🙍🏼‍♀️", []string{"woman frowning: medium-light skin tone"}},
					emoji{"🙍🏼‍♀", []string{"woman frowning: medium-light skin tone"}},
					emoji{"🙍🏽‍♀️", []string{"woman frowning: medium skin tone"}},
					emoji{"🙍🏽‍♀", []string{"woman frowning: medium skin tone"}},
					emoji{"🙍🏾‍♀️", []string{"woman frowning: medium-dark skin tone"}},
					emoji{"🙍🏾‍♀", []string{"woman frowning: medium-dark skin tone"}},
					emoji{"🙍🏿‍♀️", []string{"woman frowning: dark skin tone"}},
					emoji{"🙍🏿‍♀", []string{"woman frowning: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"pouting"},
				Emojis: []emoji{
					emoji{"🙎", []string{"person pouting"}},
					emoji{"🙎🏻", []string{"person pouting: light skin tone"}},
					emoji{"🙎🏼", []string{"person pouting: medium-light skin tone"}},
					emoji{"🙎🏽", []string{"person pouting: medium skin tone"}},
					emoji{"🙎🏾", []string{"person pouting: medium-dark skin tone"}},
					emoji{"🙎🏿", []string{"person pouting: dark skin tone"}},
					emoji{"🙎‍♂️", []string{"man pouting"}},
					emoji{"🙎‍♂", []string{"man pouting"}},
					emoji{"🙎🏻‍♂️", []string{"man pouting: light skin tone"}},
					emoji{"🙎🏻‍♂", []string{"man pouting: light skin tone"}},
					emoji{"🙎🏼‍♂️", []string{"man pouting: medium-light skin tone"}},
					emoji{"🙎🏼‍♂", []string{"man pouting: medium-light skin tone"}},
					emoji{"🙎🏽‍♂️", []string{"man pouting: medium skin tone"}},
					emoji{"🙎🏽‍♂", []string{"man pouting: medium skin tone"}},
					emoji{"🙎🏾‍♂️", []string{"man pouting: medium-dark skin tone"}},
					emoji{"🙎🏾‍♂", []string{"man pouting: medium-dark skin tone"}},
					emoji{"🙎🏿‍♂️", []string{"man pouting: dark skin tone"}},
					emoji{"🙎🏿‍♂", []string{"man pouting: dark skin tone"}},
					emoji{"🙎‍♀️", []string{"woman pouting"}},
					emoji{"🙎‍♀", []string{"woman pouting"}},
					emoji{"🙎🏻‍♀️", []string{"woman pouting: light skin tone"}},
					emoji{"🙎🏻‍♀", []string{"woman pouting: light skin tone"}},
					emoji{"🙎🏼‍♀️", []string{"woman pouting: medium-light skin tone"}},
					emoji{"🙎🏼‍♀", []string{"woman pouting: medium-light skin tone"}},
					emoji{"🙎🏽‍♀️", []string{"woman pouting: medium skin tone"}},
					emoji{"🙎🏽‍♀", []string{"woman pouting: medium skin tone"}},
					emoji{"🙎🏾‍♀️", []string{"woman pouting: medium-dark skin tone"}},
					emoji{"🙎🏾‍♀", []string{"woman pouting: medium-dark skin tone"}},
					emoji{"🙎🏿‍♀️", []string{"woman pouting: dark skin tone"}},
					emoji{"🙎🏿‍♀", []string{"woman pouting: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"gesturing-NO"},
				Emojis: []emoji{
					emoji{"🙅", []string{"person gesturing NO"}},
					emoji{"🙅🏻", []string{"person gesturing NO: light skin tone"}},
					emoji{"🙅🏼", []string{"person gesturing NO: medium-light skin tone"}},
					emoji{"🙅🏽", []string{"person gesturing NO: medium skin tone"}},
					emoji{"🙅🏾", []string{"person gesturing NO: medium-dark skin tone"}},
					emoji{"🙅🏿", []string{"person gesturing NO: dark skin tone"}},
					emoji{"🙅‍♂️", []string{"man gesturing NO"}},
					emoji{"🙅‍♂", []string{"man gesturing NO"}},
					emoji{"🙅🏻‍♂️", []string{"man gesturing NO: light skin tone"}},
					emoji{"🙅🏻‍♂", []string{"man gesturing NO: light skin tone"}},
					emoji{"🙅🏼‍♂️", []string{"man gesturing NO: medium-light skin tone"}},
					emoji{"🙅🏼‍♂", []string{"man gesturing NO: medium-light skin tone"}},
					emoji{"🙅🏽‍♂️", []string{"man gesturing NO: medium skin tone"}},
					emoji{"🙅🏽‍♂", []string{"man gesturing NO: medium skin tone"}},
					emoji{"🙅🏾‍♂️", []string{"man gesturing NO: medium-dark skin tone"}},
					emoji{"🙅🏾‍♂", []string{"man gesturing NO: medium-dark skin tone"}},
					emoji{"🙅🏿‍♂️", []string{"man gesturing NO: dark skin tone"}},
					emoji{"🙅🏿‍♂", []string{"man gesturing NO: dark skin tone"}},
					emoji{"🙅‍♀️", []string{"woman gesturing NO"}},
					emoji{"🙅‍♀", []string{"woman gesturing NO"}},
					emoji{"🙅🏻‍♀️", []string{"woman gesturing NO: light skin tone"}},
					emoji{"🙅🏻‍♀", []string{"woman gesturing NO: light skin tone"}},
					emoji{"🙅🏼‍♀️", []string{"woman gesturing NO: medium-light skin tone"}},
					emoji{"🙅🏼‍♀", []string{"woman gesturing NO: medium-light skin tone"}},
					emoji{"🙅🏽‍♀️", []string{"woman gesturing NO: medium skin tone"}},
					emoji{"🙅🏽‍♀", []string{"woman gesturing NO: medium skin tone"}},
					emoji{"🙅🏾‍♀️", []string{"woman gesturing NO: medium-dark skin tone"}},
					emoji{"🙅🏾‍♀", []string{"woman gesturing NO: medium-dark skin tone"}},
					emoji{"🙅🏿‍♀️", []string{"woman gesturing NO: dark skin tone"}},
					emoji{"🙅🏿‍♀", []string{"woman gesturing NO: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"gesturing-OK"},
				Emojis: []emoji{
					emoji{"🙆", []string{"person gesturing OK"}},
					emoji{"🙆🏻", []string{"person gesturing OK: light skin tone"}},
					emoji{"🙆🏼", []string{"person gesturing OK: medium-light skin tone"}},
					emoji{"🙆🏽", []string{"person gesturing OK: medium skin tone"}},
					emoji{"🙆🏾", []string{"person gesturing OK: medium-dark skin tone"}},
					emoji{"🙆🏿", []string{"person gesturing OK: dark skin tone"}},
					emoji{"🙆‍♂️", []string{"man gesturing OK"}},
					emoji{"🙆‍♂", []string{"man gesturing OK"}},
					emoji{"🙆🏻‍♂️", []string{"man gesturing OK: light skin tone"}},
					emoji{"🙆🏻‍♂", []string{"man gesturing OK: light skin tone"}},
					emoji{"🙆🏼‍♂️", []string{"man gesturing OK: medium-light skin tone"}},
					emoji{"🙆🏼‍♂", []string{"man gesturing OK: medium-light skin tone"}},
					emoji{"🙆🏽‍♂️", []string{"man gesturing OK: medium skin tone"}},
					emoji{"🙆🏽‍♂", []string{"man gesturing OK: medium skin tone"}},
					emoji{"🙆🏾‍♂️", []string{"man gesturing OK: medium-dark skin tone"}},
					emoji{"🙆🏾‍♂", []string{"man gesturing OK: medium-dark skin tone"}},
					emoji{"🙆🏿‍♂️", []string{"man gesturing OK: dark skin tone"}},
					emoji{"🙆🏿‍♂", []string{"man gesturing OK: dark skin tone"}},
					emoji{"🙆‍♀️", []string{"woman gesturing OK"}},
					emoji{"🙆‍♀", []string{"woman gesturing OK"}},
					emoji{"🙆🏻‍♀️", []string{"woman gesturing OK: light skin tone"}},
					emoji{"🙆🏻‍♀", []string{"woman gesturing OK: light skin tone"}},
					emoji{"🙆🏼‍♀️", []string{"woman gesturing OK: medium-light skin tone"}},
					emoji{"🙆🏼‍♀", []string{"woman gesturing OK: medium-light skin tone"}},
					emoji{"🙆🏽‍♀️", []string{"woman gesturing OK: medium skin tone"}},
					emoji{"🙆🏽‍♀", []string{"woman gesturing OK: medium skin tone"}},
					emoji{"🙆🏾‍♀️", []string{"woman gesturing OK: medium-dark skin tone"}},
					emoji{"🙆🏾‍♀", []string{"woman gesturing OK: medium-dark skin tone"}},
					emoji{"🙆🏿‍♀️", []string{"woman gesturing OK: dark skin tone"}},
					emoji{"🙆🏿‍♀", []string{"woman gesturing OK: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"tipping-hand"},
				Emojis: []emoji{
					emoji{"💁", []string{"person tipping hand"}},
					emoji{"💁🏻", []string{"person tipping hand: light skin tone"}},
					emoji{"💁🏼", []string{"person tipping hand: medium-light skin tone"}},
					emoji{"💁🏽", []string{"person tipping hand: medium skin tone"}},
					emoji{"💁🏾", []string{"person tipping hand: medium-dark skin tone"}},
					emoji{"💁🏿", []string{"person tipping hand: dark skin tone"}},
					emoji{"💁‍♂️", []string{"man tipping hand"}},
					emoji{"💁‍♂", []string{"man tipping hand"}},
					emoji{"💁🏻‍♂️", []string{"man tipping hand: light skin tone"}},
					emoji{"💁🏻‍♂", []string{"man tipping hand: light skin tone"}},
					emoji{"💁🏼‍♂️", []string{"man tipping hand: medium-light skin tone"}},
					emoji{"💁🏼‍♂", []string{"man tipping hand: medium-light skin tone"}},
					emoji{"💁🏽‍♂️", []string{"man tipping hand: medium skin tone"}},
					emoji{"💁🏽‍♂", []string{"man tipping hand: medium skin tone"}},
					emoji{"💁🏾‍♂️", []string{"man tipping hand: medium-dark skin tone"}},
					emoji{"💁🏾‍♂", []string{"man tipping hand: medium-dark skin tone"}},
					emoji{"💁🏿‍♂️", []string{"man tipping hand: dark skin tone"}},
					emoji{"💁🏿‍♂", []string{"man tipping hand: dark skin tone"}},
					emoji{"💁‍♀️", []string{"woman tipping hand"}},
					emoji{"💁‍♀", []string{"woman tipping hand"}},
					emoji{"💁🏻‍♀️", []string{"woman tipping hand: light skin tone"}},
					emoji{"💁🏻‍♀", []string{"woman tipping hand: light skin tone"}},
					emoji{"💁🏼‍♀️", []string{"woman tipping hand: medium-light skin tone"}},
					emoji{"💁🏼‍♀", []string{"woman tipping hand: medium-light skin tone"}},
					emoji{"💁🏽‍♀️", []string{"woman tipping hand: medium skin tone"}},
					emoji{"💁🏽‍♀", []string{"woman tipping hand: medium skin tone"}},
					emoji{"💁🏾‍♀️", []string{"woman tipping hand: medium-dark skin tone"}},
					emoji{"💁🏾‍♀", []string{"woman tipping hand: medium-dark skin tone"}},
					emoji{"💁🏿‍♀️", []string{"woman tipping hand: dark skin tone"}},
					emoji{"💁🏿‍♀", []string{"woman tipping hand: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"raising-hand"},
				Emojis: []emoji{
					emoji{"🙋", []string{"person raising hand"}},
					emoji{"🙋🏻", []string{"person raising hand: light skin tone"}},
					emoji{"🙋🏼", []string{"person raising hand: medium-light skin tone"}},
					emoji{"🙋🏽", []string{"person raising hand: medium skin tone"}},
					emoji{"🙋🏾", []string{"person raising hand: medium-dark skin tone"}},
					emoji{"🙋🏿", []string{"person raising hand: dark skin tone"}},
					emoji{"🙋‍♂️", []string{"man raising hand"}},
					emoji{"🙋‍♂", []string{"man raising hand"}},
					emoji{"🙋🏻‍♂️", []string{"man raising hand: light skin tone"}},
					emoji{"🙋🏻‍♂", []string{"man raising hand: light skin tone"}},
					emoji{"🙋🏼‍♂️", []string{"man raising hand: medium-light skin tone"}},
					emoji{"🙋🏼‍♂", []string{"man raising hand: medium-light skin tone"}},
					emoji{"🙋🏽‍♂️", []string{"man raising hand: medium skin tone"}},
					emoji{"🙋🏽‍♂", []string{"man raising hand: medium skin tone"}},
					emoji{"🙋🏾‍♂️", []string{"man raising hand: medium-dark skin tone"}},
					emoji{"🙋🏾‍♂", []string{"man raising hand: medium-dark skin tone"}},
					emoji{"🙋🏿‍♂️", []string{"man raising hand: dark skin tone"}},
					emoji{"🙋🏿‍♂", []string{"man raising hand: dark skin tone"}},
					emoji{"🙋‍♀️", []string{"woman raising hand"}},
					emoji{"🙋‍♀", []string{"woman raising hand"}},
					emoji{"🙋🏻‍♀️", []string{"woman raising hand: light skin tone"}},
					emoji{"🙋🏻‍♀", []string{"woman raising hand: light skin tone"}},
					emoji{"🙋🏼‍♀️", []string{"woman raising hand: medium-light skin tone"}},
					emoji{"🙋🏼‍♀", []string{"woman raising hand: medium-light skin tone"}},
					emoji{"🙋🏽‍♀️", []string{"woman raising hand: medium skin tone"}},
					emoji{"🙋🏽‍♀", []string{"woman raising hand: medium skin tone"}},
					emoji{"🙋🏾‍♀️", []string{"woman raising hand: medium-dark skin tone"}},
					emoji{"🙋🏾‍♀", []string{"woman raising hand: medium-dark skin tone"}},
					emoji{"🙋🏿‍♀️", []string{"woman raising hand: dark skin tone"}},
					emoji{"🙋🏿‍♀", []string{"woman raising hand: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"bowing"},
				Emojis: []emoji{
					emoji{"🙇", []string{"person bowing"}},
					emoji{"🙇🏻", []string{"person bowing: light skin tone"}},
					emoji{"🙇🏼", []string{"person bowing: medium-light skin tone"}},
					emoji{"🙇🏽", []string{"person bowing: medium skin tone"}},
					emoji{"🙇🏾", []string{"person bowing: medium-dark skin tone"}},
					emoji{"🙇🏿", []string{"person bowing: dark skin tone"}},
					emoji{"🙇‍♂️", []string{"man bowing"}},
					emoji{"🙇‍♂", []string{"man bowing"}},
					emoji{"🙇🏻‍♂️", []string{"man bowing: light skin tone"}},
					emoji{"🙇🏻‍♂", []string{"man bowing: light skin tone"}},
					emoji{"🙇🏼‍♂️", []string{"man bowing: medium-light skin tone"}},
					emoji{"🙇🏼‍♂", []string{"man bowing: medium-light skin tone"}},
					emoji{"🙇🏽‍♂️", []string{"man bowing: medium skin tone"}},
					emoji{"🙇🏽‍♂", []string{"man bowing: medium skin tone"}},
					emoji{"🙇🏾‍♂️", []string{"man bowing: medium-dark skin tone"}},
					emoji{"🙇🏾‍♂", []string{"man bowing: medium-dark skin tone"}},
					emoji{"🙇🏿‍♂️", []string{"man bowing: dark skin tone"}},
					emoji{"🙇🏿‍♂", []string{"man bowing: dark skin tone"}},
					emoji{"🙇‍♀️", []string{"woman bowing"}},
					emoji{"🙇‍♀", []string{"woman bowing"}},
					emoji{"🙇🏻‍♀️", []string{"woman bowing: light skin tone"}},
					emoji{"🙇🏻‍♀", []string{"woman bowing: light skin tone"}},
					emoji{"🙇🏼‍♀️", []string{"woman bowing: medium-light skin tone"}},
					emoji{"🙇🏼‍♀", []string{"woman bowing: medium-light skin tone"}},
					emoji{"🙇🏽‍♀️", []string{"woman bowing: medium skin tone"}},
					emoji{"🙇🏽‍♀", []string{"woman bowing: medium skin tone"}},
					emoji{"🙇🏾‍♀️", []string{"woman bowing: medium-dark skin tone"}},
					emoji{"🙇🏾‍♀", []string{"woman bowing: medium-dark skin tone"}},
					emoji{"🙇🏿‍♀️", []string{"woman bowing: dark skin tone"}},
					emoji{"🙇🏿‍♀", []string{"woman bowing: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"facepalming"},
				Emojis: []emoji{
					emoji{"🤦", []string{"person facepalming"}},
					emoji{"🤦🏻", []string{"person facepalming: light skin tone"}},
					emoji{"🤦🏼", []string{"person facepalming: medium-light skin tone"}},
					emoji{"🤦🏽", []string{"person facepalming: medium skin tone"}},
					emoji{"🤦🏾", []string{"person facepalming: medium-dark skin tone"}},
					emoji{"🤦🏿", []string{"person facepalming: dark skin tone"}},
					emoji{"🤦‍♂️", []string{"man facepalming"}},
					emoji{"🤦‍♂", []string{"man facepalming"}},
					emoji{"🤦🏻‍♂️", []string{"man facepalming: light skin tone"}},
					emoji{"🤦🏻‍♂", []string{"man facepalming: light skin tone"}},
					emoji{"🤦🏼‍♂️", []string{"man facepalming: medium-light skin tone"}},
					emoji{"🤦🏼‍♂", []string{"man facepalming: medium-light skin tone"}},
					emoji{"🤦🏽‍♂️", []string{"man facepalming: medium skin tone"}},
					emoji{"🤦🏽‍♂", []string{"man facepalming: medium skin tone"}},
					emoji{"🤦🏾‍♂️", []string{"man facepalming: medium-dark skin tone"}},
					emoji{"🤦🏾‍♂", []string{"man facepalming: medium-dark skin tone"}},
					emoji{"🤦🏿‍♂️", []string{"man facepalming: dark skin tone"}},
					emoji{"🤦🏿‍♂", []string{"man facepalming: dark skin tone"}},
					emoji{"🤦‍♀️", []string{"woman facepalming"}},
					emoji{"🤦‍♀", []string{"woman facepalming"}},
					emoji{"🤦🏻‍♀️", []string{"woman facepalming: light skin tone"}},
					emoji{"🤦🏻‍♀", []string{"woman facepalming: light skin tone"}},
					emoji{"🤦🏼‍♀️", []string{"woman facepalming: medium-light skin tone"}},
					emoji{"🤦🏼‍♀", []string{"woman facepalming: medium-light skin tone"}},
					emoji{"🤦🏽‍♀️", []string{"woman facepalming: medium skin tone"}},
					emoji{"🤦🏽‍♀", []string{"woman facepalming: medium skin tone"}},
					emoji{"🤦🏾‍♀️", []string{"woman facepalming: medium-dark skin tone"}},
					emoji{"🤦🏾‍♀", []string{"woman facepalming: medium-dark skin tone"}},
					emoji{"🤦🏿‍♀️", []string{"woman facepalming: dark skin tone"}},
					emoji{"🤦🏿‍♀", []string{"woman facepalming: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"shrugging"},
				Emojis: []emoji{
					emoji{"🤷", []string{"person shrugging"}},
					emoji{"🤷🏻", []string{"person shrugging: light skin tone"}},
					emoji{"🤷🏼", []string{"person shrugging: medium-light skin tone"}},
					emoji{"🤷🏽", []string{"person shrugging: medium skin tone"}},
					emoji{"🤷🏾", []string{"person shrugging: medium-dark skin tone"}},
					emoji{"🤷🏿", []string{"person shrugging: dark skin tone"}},
					emoji{"🤷‍♂️", []string{"man shrugging"}},
					emoji{"🤷‍♂", []string{"man shrugging"}},
					emoji{"🤷🏻‍♂️", []string{"man shrugging: light skin tone"}},
					emoji{"🤷🏻‍♂", []string{"man shrugging: light skin tone"}},
					emoji{"🤷🏼‍♂️", []string{"man shrugging: medium-light skin tone"}},
					emoji{"🤷🏼‍♂", []string{"man shrugging: medium-light skin tone"}},
					emoji{"🤷🏽‍♂️", []string{"man shrugging: medium skin tone"}},
					emoji{"🤷🏽‍♂", []string{"man shrugging: medium skin tone"}},
					emoji{"🤷🏾‍♂️", []string{"man shrugging: medium-dark skin tone"}},
					emoji{"🤷🏾‍♂", []string{"man shrugging: medium-dark skin tone"}},
					emoji{"🤷🏿‍♂️", []string{"man shrugging: dark skin tone"}},
					emoji{"🤷🏿‍♂", []string{"man shrugging: dark skin tone"}},
					emoji{"🤷‍♀️", []string{"woman shrugging"}},
					emoji{"🤷‍♀", []string{"woman shrugging"}},
					emoji{"🤷🏻‍♀️", []string{"woman shrugging: light skin tone"}},
					emoji{"🤷🏻‍♀", []string{"woman shrugging: light skin tone"}},
					emoji{"🤷🏼‍♀️", []string{"woman shrugging: medium-light skin tone"}},
					emoji{"🤷🏼‍♀", []string{"woman shrugging: medium-light skin tone"}},
					emoji{"🤷🏽‍♀️", []string{"woman shrugging: medium skin tone"}},
					emoji{"🤷🏽‍♀", []string{"woman shrugging: medium skin tone"}},
					emoji{"🤷🏾‍♀️", []string{"woman shrugging: medium-dark skin tone"}},
					emoji{"🤷🏾‍♀", []string{"woman shrugging: medium-dark skin tone"}},
					emoji{"🤷🏿‍♀️", []string{"woman shrugging: dark skin tone"}},
					emoji{"🤷🏿‍♀", []string{"woman shrugging: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"person-massage"},
				Emojis: []emoji{
					emoji{"💆", []string{"person getting massage"}},
					emoji{"💆🏻", []string{"person getting massage: light skin tone"}},
					emoji{"💆🏼", []string{"person getting massage: medium-light skin tone"}},
					emoji{"💆🏽", []string{"person getting massage: medium skin tone"}},
					emoji{"💆🏾", []string{"person getting massage: medium-dark skin tone"}},
					emoji{"💆🏿", []string{"person getting massage: dark skin tone"}},
					emoji{"💆‍♂️", []string{"man getting massage"}},
					emoji{"💆‍♂", []string{"man getting massage"}},
					emoji{"💆🏻‍♂️", []string{"man getting massage: light skin tone"}},
					emoji{"💆🏻‍♂", []string{"man getting massage: light skin tone"}},
					emoji{"💆🏼‍♂️", []string{"man getting massage: medium-light skin tone"}},
					emoji{"💆🏼‍♂", []string{"man getting massage: medium-light skin tone"}},
					emoji{"💆🏽‍♂️", []string{"man getting massage: medium skin tone"}},
					emoji{"💆🏽‍♂", []string{"man getting massage: medium skin tone"}},
					emoji{"💆🏾‍♂️", []string{"man getting massage: medium-dark skin tone"}},
					emoji{"💆🏾‍♂", []string{"man getting massage: medium-dark skin tone"}},
					emoji{"💆🏿‍♂️", []string{"man getting massage: dark skin tone"}},
					emoji{"💆🏿‍♂", []string{"man getting massage: dark skin tone"}},
					emoji{"💆‍♀️", []string{"woman getting massage"}},
					emoji{"💆‍♀", []string{"woman getting massage"}},
					emoji{"💆🏻‍♀️", []string{"woman getting massage: light skin tone"}},
					emoji{"💆🏻‍♀", []string{"woman getting massage: light skin tone"}},
					emoji{"💆🏼‍♀️", []string{"woman getting massage: medium-light skin tone"}},
					emoji{"💆🏼‍♀", []string{"woman getting massage: medium-light skin tone"}},
					emoji{"💆🏽‍♀️", []string{"woman getting massage: medium skin tone"}},
					emoji{"💆🏽‍♀", []string{"woman getting massage: medium skin tone"}},
					emoji{"💆🏾‍♀️", []string{"woman getting massage: medium-dark skin tone"}},
					emoji{"💆🏾‍♀", []string{"woman getting massage: medium-dark skin tone"}},
					emoji{"💆🏿‍♀️", []string{"woman getting massage: dark skin tone"}},
					emoji{"💆🏿‍♀", []string{"woman getting massage: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"haircut"},
				Emojis: []emoji{
					emoji{"💇", []string{"person getting haircut"}},
					emoji{"💇🏻", []string{"person getting haircut: light skin tone"}},
					emoji{"💇🏼", []string{"person getting haircut: medium-light skin tone"}},
					emoji{"💇🏽", []string{"person getting haircut: medium skin tone"}},
					emoji{"💇🏾", []string{"person getting haircut: medium-dark skin tone"}},
					emoji{"💇🏿", []string{"person getting haircut: dark skin tone"}},
					emoji{"💇‍♂️", []string{"man getting haircut"}},
					emoji{"💇‍♂", []string{"man getting haircut"}},
					emoji{"💇🏻‍♂️", []string{"man getting haircut: light skin tone"}},
					emoji{"💇🏻‍♂", []string{"man getting haircut: light skin tone"}},
					emoji{"💇🏼‍♂️", []string{"man getting haircut: medium-light skin tone"}},
					emoji{"💇🏼‍♂", []string{"man getting haircut: medium-light skin tone"}},
					emoji{"💇🏽‍♂️", []string{"man getting haircut: medium skin tone"}},
					emoji{"💇🏽‍♂", []string{"man getting haircut: medium skin tone"}},
					emoji{"💇🏾‍♂️", []string{"man getting haircut: medium-dark skin tone"}},
					emoji{"💇🏾‍♂", []string{"man getting haircut: medium-dark skin tone"}},
					emoji{"💇🏿‍♂️", []string{"man getting haircut: dark skin tone"}},
					emoji{"💇🏿‍♂", []string{"man getting haircut: dark skin tone"}},
					emoji{"💇‍♀️", []string{"woman getting haircut"}},
					emoji{"💇‍♀", []string{"woman getting haircut"}},
					emoji{"💇🏻‍♀️", []string{"woman getting haircut: light skin tone"}},
					emoji{"💇🏻‍♀", []string{"woman getting haircut: light skin tone"}},
					emoji{"💇🏼‍♀️", []string{"woman getting haircut: medium-light skin tone"}},
					emoji{"💇🏼‍♀", []string{"woman getting haircut: medium-light skin tone"}},
					emoji{"💇🏽‍♀️", []string{"woman getting haircut: medium skin tone"}},
					emoji{"💇🏽‍♀", []string{"woman getting haircut: medium skin tone"}},
					emoji{"💇🏾‍♀️", []string{"woman getting haircut: medium-dark skin tone"}},
					emoji{"💇🏾‍♀", []string{"woman getting haircut: medium-dark skin tone"}},
					emoji{"💇🏿‍♀️", []string{"woman getting haircut: dark skin tone"}},
					emoji{"💇🏿‍♀", []string{"woman getting haircut: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"walking"},
				Emojis: []emoji{
					emoji{"🚶", []string{"person walking"}},
					emoji{"🚶🏻", []string{"person walking: light skin tone"}},
					emoji{"🚶🏼", []string{"person walking: medium-light skin tone"}},
					emoji{"🚶🏽", []string{"person walking: medium skin tone"}},
					emoji{"🚶🏾", []string{"person walking: medium-dark skin tone"}},
					emoji{"🚶🏿", []string{"person walking: dark skin tone"}},
					emoji{"🚶‍♂️", []string{"man walking"}},
					emoji{"🚶‍♂", []string{"man walking"}},
					emoji{"🚶🏻‍♂️", []string{"man walking: light skin tone"}},
					emoji{"🚶🏻‍♂", []string{"man walking: light skin tone"}},
					emoji{"🚶🏼‍♂️", []string{"man walking: medium-light skin tone"}},
					emoji{"🚶🏼‍♂", []string{"man walking: medium-light skin tone"}},
					emoji{"🚶🏽‍♂️", []string{"man walking: medium skin tone"}},
					emoji{"🚶🏽‍♂", []string{"man walking: medium skin tone"}},
					emoji{"🚶🏾‍♂️", []string{"man walking: medium-dark skin tone"}},
					emoji{"🚶🏾‍♂", []string{"man walking: medium-dark skin tone"}},
					emoji{"🚶🏿‍♂️", []string{"man walking: dark skin tone"}},
					emoji{"🚶🏿‍♂", []string{"man walking: dark skin tone"}},
					emoji{"🚶‍♀️", []string{"woman walking"}},
					emoji{"🚶‍♀", []string{"woman walking"}},
					emoji{"🚶🏻‍♀️", []string{"woman walking: light skin tone"}},
					emoji{"🚶🏻‍♀", []string{"woman walking: light skin tone"}},
					emoji{"🚶🏼‍♀️", []string{"woman walking: medium-light skin tone"}},
					emoji{"🚶🏼‍♀", []string{"woman walking: medium-light skin tone"}},
					emoji{"🚶🏽‍♀️", []string{"woman walking: medium skin tone"}},
					emoji{"🚶🏽‍♀", []string{"woman walking: medium skin tone"}},
					emoji{"🚶🏾‍♀️", []string{"woman walking: medium-dark skin tone"}},
					emoji{"🚶🏾‍♀", []string{"woman walking: medium-dark skin tone"}},
					emoji{"🚶🏿‍♀️", []string{"woman walking: dark skin tone"}},
					emoji{"🚶🏿‍♀", []string{"woman walking: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"running"},
				Emojis: []emoji{
					emoji{"🏃", []string{"person running"}},
					emoji{"🏃🏻", []string{"person running: light skin tone"}},
					emoji{"🏃🏼", []string{"person running: medium-light skin tone"}},
					emoji{"🏃🏽", []string{"person running: medium skin tone"}},
					emoji{"🏃🏾", []string{"person running: medium-dark skin tone"}},
					emoji{"🏃🏿", []string{"person running: dark skin tone"}},
					emoji{"🏃‍♂️", []string{"man running"}},
					emoji{"🏃‍♂", []string{"man running"}},
					emoji{"🏃🏻‍♂️", []string{"man running: light skin tone"}},
					emoji{"🏃🏻‍♂", []string{"man running: light skin tone"}},
					emoji{"🏃🏼‍♂️", []string{"man running: medium-light skin tone"}},
					emoji{"🏃🏼‍♂", []string{"man running: medium-light skin tone"}},
					emoji{"🏃🏽‍♂️", []string{"man running: medium skin tone"}},
					emoji{"🏃🏽‍♂", []string{"man running: medium skin tone"}},
					emoji{"🏃🏾‍♂️", []string{"man running: medium-dark skin tone"}},
					emoji{"🏃🏾‍♂", []string{"man running: medium-dark skin tone"}},
					emoji{"🏃🏿‍♂️", []string{"man running: dark skin tone"}},
					emoji{"🏃🏿‍♂", []string{"man running: dark skin tone"}},
					emoji{"🏃‍♀️", []string{"woman running"}},
					emoji{"🏃‍♀", []string{"woman running"}},
					emoji{"🏃🏻‍♀️", []string{"woman running: light skin tone"}},
					emoji{"🏃🏻‍♀", []string{"woman running: light skin tone"}},
					emoji{"🏃🏼‍♀️", []string{"woman running: medium-light skin tone"}},
					emoji{"🏃🏼‍♀", []string{"woman running: medium-light skin tone"}},
					emoji{"🏃🏽‍♀️", []string{"woman running: medium skin tone"}},
					emoji{"🏃🏽‍♀", []string{"woman running: medium skin tone"}},
					emoji{"🏃🏾‍♀️", []string{"woman running: medium-dark skin tone"}},
					emoji{"🏃🏾‍♀", []string{"woman running: medium-dark skin tone"}},
					emoji{"🏃🏿‍♀️", []string{"woman running: dark skin tone"}},
					emoji{"🏃🏿‍♀", []string{"woman running: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"dancing"},
				Emojis: []emoji{
					emoji{"💃", []string{"woman dancing"}},
					emoji{"💃🏻", []string{"woman dancing: light skin tone"}},
					emoji{"💃🏼", []string{"woman dancing: medium-light skin tone"}},
					emoji{"💃🏽", []string{"woman dancing: medium skin tone"}},
					emoji{"💃🏾", []string{"woman dancing: medium-dark skin tone"}},
					emoji{"💃🏿", []string{"woman dancing: dark skin tone"}},
					emoji{"🕺", []string{"man dancing"}},
					emoji{"🕺🏻", []string{"man dancing: light skin tone"}},
					emoji{"🕺🏼", []string{"man dancing: medium-light skin tone"}},
					emoji{"🕺🏽", []string{"man dancing: medium skin tone"}},
					emoji{"🕺🏾", []string{"man dancing: medium-dark skin tone"}},
					emoji{"🕺🏿", []string{"man dancing: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"bunny-ears"},
				Emojis: []emoji{
					emoji{"👯", []string{"people with bunny ears"}},
					emoji{"👯‍♂️", []string{"men with bunny ears"}},
					emoji{"👯‍♂", []string{"men with bunny ears"}},
					emoji{"👯‍♀️", []string{"women with bunny ears"}},
					emoji{"👯‍♀", []string{"women with bunny ears"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"steamy"},
				Emojis: []emoji{
					emoji{"🧖", []string{"person in steamy room"}},
					emoji{"🧖🏻", []string{"person in steamy room: light skin tone"}},
					emoji{"🧖🏼", []string{"person in steamy room: medium-light skin tone"}},
					emoji{"🧖🏽", []string{"person in steamy room: medium skin tone"}},
					emoji{"🧖🏾", []string{"person in steamy room: medium-dark skin tone"}},
					emoji{"🧖🏿", []string{"person in steamy room: dark skin tone"}},
					emoji{"🧖‍♀️", []string{"woman in steamy room"}},
					emoji{"🧖‍♀", []string{"woman in steamy room"}},
					emoji{"🧖🏻‍♀️", []string{"woman in steamy room: light skin tone"}},
					emoji{"🧖🏻‍♀", []string{"woman in steamy room: light skin tone"}},
					emoji{"🧖🏼‍♀️", []string{"woman in steamy room: medium-light skin tone"}},
					emoji{"🧖🏼‍♀", []string{"woman in steamy room: medium-light skin tone"}},
					emoji{"🧖🏽‍♀️", []string{"woman in steamy room: medium skin tone"}},
					emoji{"🧖🏽‍♀", []string{"woman in steamy room: medium skin tone"}},
					emoji{"🧖🏾‍♀️", []string{"woman in steamy room: medium-dark skin tone"}},
					emoji{"🧖🏾‍♀", []string{"woman in steamy room: medium-dark skin tone"}},
					emoji{"🧖🏿‍♀️", []string{"woman in steamy room: dark skin tone"}},
					emoji{"🧖🏿‍♀", []string{"woman in steamy room: dark skin tone"}},
					emoji{"🧖‍♂️", []string{"man in steamy room"}},
					emoji{"🧖‍♂", []string{"man in steamy room"}},
					emoji{"🧖🏻‍♂️", []string{"man in steamy room: light skin tone"}},
					emoji{"🧖🏻‍♂", []string{"man in steamy room: light skin tone"}},
					emoji{"🧖🏼‍♂️", []string{"man in steamy room: medium-light skin tone"}},
					emoji{"🧖🏼‍♂", []string{"man in steamy room: medium-light skin tone"}},
					emoji{"🧖🏽‍♂️", []string{"man in steamy room: medium skin tone"}},
					emoji{"🧖🏽‍♂", []string{"man in steamy room: medium skin tone"}},
					emoji{"🧖🏾‍♂️", []string{"man in steamy room: medium-dark skin tone"}},
					emoji{"🧖🏾‍♂", []string{"man in steamy room: medium-dark skin tone"}},
					emoji{"🧖🏿‍♂️", []string{"man in steamy room: dark skin tone"}},
					emoji{"🧖🏿‍♂", []string{"man in steamy room: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"climbing"},
				Emojis: []emoji{
					emoji{"🧗", []string{"person climbing"}},
					emoji{"🧗🏻", []string{"person climbing: light skin tone"}},
					emoji{"🧗🏼", []string{"person climbing: medium-light skin tone"}},
					emoji{"🧗🏽", []string{"person climbing: medium skin tone"}},
					emoji{"🧗🏾", []string{"person climbing: medium-dark skin tone"}},
					emoji{"🧗🏿", []string{"person climbing: dark skin tone"}},
					emoji{"🧗‍♀️", []string{"woman climbing"}},
					emoji{"🧗‍♀", []string{"woman climbing"}},
					emoji{"🧗🏻‍♀️", []string{"woman climbing: light skin tone"}},
					emoji{"🧗🏻‍♀", []string{"woman climbing: light skin tone"}},
					emoji{"🧗🏼‍♀️", []string{"woman climbing: medium-light skin tone"}},
					emoji{"🧗🏼‍♀", []string{"woman climbing: medium-light skin tone"}},
					emoji{"🧗🏽‍♀️", []string{"woman climbing: medium skin tone"}},
					emoji{"🧗🏽‍♀", []string{"woman climbing: medium skin tone"}},
					emoji{"🧗🏾‍♀️", []string{"woman climbing: medium-dark skin tone"}},
					emoji{"🧗🏾‍♀", []string{"woman climbing: medium-dark skin tone"}},
					emoji{"🧗🏿‍♀️", []string{"woman climbing: dark skin tone"}},
					emoji{"🧗🏿‍♀", []string{"woman climbing: dark skin tone"}},
					emoji{"🧗‍♂️", []string{"man climbing"}},
					emoji{"🧗‍♂", []string{"man climbing"}},
					emoji{"🧗🏻‍♂️", []string{"man climbing: light skin tone"}},
					emoji{"🧗🏻‍♂", []string{"man climbing: light skin tone"}},
					emoji{"🧗🏼‍♂️", []string{"man climbing: medium-light skin tone"}},
					emoji{"🧗🏼‍♂", []string{"man climbing: medium-light skin tone"}},
					emoji{"🧗🏽‍♂️", []string{"man climbing: medium skin tone"}},
					emoji{"🧗🏽‍♂", []string{"man climbing: medium skin tone"}},
					emoji{"🧗🏾‍♂️", []string{"man climbing: medium-dark skin tone"}},
					emoji{"🧗🏾‍♂", []string{"man climbing: medium-dark skin tone"}},
					emoji{"🧗🏿‍♂️", []string{"man climbing: dark skin tone"}},
					emoji{"🧗🏿‍♂", []string{"man climbing: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"lotus"},
				Emojis: []emoji{
					emoji{"🧘", []string{"person in lotus position"}},
					emoji{"🧘🏻", []string{"person in lotus position: light skin tone"}},
					emoji{"🧘🏼", []string{"person in lotus position: medium-light skin tone"}},
					emoji{"🧘🏽", []string{"person in lotus position: medium skin tone"}},
					emoji{"🧘🏾", []string{"person in lotus position: medium-dark skin tone"}},
					emoji{"🧘🏿", []string{"person in lotus position: dark skin tone"}},
					emoji{"🧘‍♀️", []string{"woman in lotus position"}},
					emoji{"🧘‍♀", []string{"woman in lotus position"}},
					emoji{"🧘🏻‍♀️", []string{"woman in lotus position: light skin tone"}},
					emoji{"🧘🏻‍♀", []string{"woman in lotus position: light skin tone"}},
					emoji{"🧘🏼‍♀️", []string{"woman in lotus position: medium-light skin tone"}},
					emoji{"🧘🏼‍♀", []string{"woman in lotus position: medium-light skin tone"}},
					emoji{"🧘🏽‍♀️", []string{"woman in lotus position: medium skin tone"}},
					emoji{"🧘🏽‍♀", []string{"woman in lotus position: medium skin tone"}},
					emoji{"🧘🏾‍♀️", []string{"woman in lotus position: medium-dark skin tone"}},
					emoji{"🧘🏾‍♀", []string{"woman in lotus position: medium-dark skin tone"}},
					emoji{"🧘🏿‍♀️", []string{"woman in lotus position: dark skin tone"}},
					emoji{"🧘🏿‍♀", []string{"woman in lotus position: dark skin tone"}},
					emoji{"🧘‍♂️", []string{"man in lotus position"}},
					emoji{"🧘‍♂", []string{"man in lotus position"}},
					emoji{"🧘🏻‍♂️", []string{"man in lotus position: light skin tone"}},
					emoji{"🧘🏻‍♂", []string{"man in lotus position: light skin tone"}},
					emoji{"🧘🏼‍♂️", []string{"man in lotus position: medium-light skin tone"}},
					emoji{"🧘🏼‍♂", []string{"man in lotus position: medium-light skin tone"}},
					emoji{"🧘🏽‍♂️", []string{"man in lotus position: medium skin tone"}},
					emoji{"🧘🏽‍♂", []string{"man in lotus position: medium skin tone"}},
					emoji{"🧘🏾‍♂️", []string{"man in lotus position: medium-dark skin tone"}},
					emoji{"🧘🏾‍♂", []string{"man in lotus position: medium-dark skin tone"}},
					emoji{"🧘🏿‍♂️", []string{"man in lotus position: dark skin tone"}},
					emoji{"🧘🏿‍♂", []string{"man in lotus position: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"bath"},
				Emojis: []emoji{
					emoji{"🛀", []string{"person taking bath"}},
					emoji{"🛀🏻", []string{"person taking bath: light skin tone"}},
					emoji{"🛀🏼", []string{"person taking bath: medium-light skin tone"}},
					emoji{"🛀🏽", []string{"person taking bath: medium skin tone"}},
					emoji{"🛀🏾", []string{"person taking bath: medium-dark skin tone"}},
					emoji{"🛀🏿", []string{"person taking bath: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"bed"},
				Emojis: []emoji{
					emoji{"🛌", []string{"person in bed"}},
					emoji{"🛌🏻", []string{"person in bed: light skin tone"}},
					emoji{"🛌🏼", []string{"person in bed: medium-light skin tone"}},
					emoji{"🛌🏽", []string{"person in bed: medium skin tone"}},
					emoji{"🛌🏾", []string{"person in bed: medium-dark skin tone"}},
					emoji{"🛌🏿", []string{"person in bed: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"levitating"},
				Emojis: []emoji{
					emoji{"🕴️", []string{"man in suit levitating"}},
					emoji{"🕴", []string{"man in suit levitating"}},
					emoji{"🕴🏻", []string{"man in suit levitating: light skin tone"}},
					emoji{"🕴🏼", []string{"man in suit levitating: medium-light skin tone"}},
					emoji{"🕴🏽", []string{"man in suit levitating: medium skin tone"}},
					emoji{"🕴🏾", []string{"man in suit levitating: medium-dark skin tone"}},
					emoji{"🕴🏿", []string{"man in suit levitating: dark skin tone"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"speaking"},
				Emojis: []emoji{
					emoji{"🗣️", []string{"speaking head"}},
					emoji{"🗣", []string{"speaking head"}},
				},
			},
			subGroup{
				Group:         "people",
				SubGroupNames: []string{"silhouette"},
				Emojis: []emoji{
					emoji{"👤", []string{"bust in silhouette"}},
					emoji{"👥", []string{"busts in silhouette"}},
				},
			},
		},
	}
}
